### ISSUE TITLE
Export is not working on Retrospective board

### ISSUE THREAD

**Issue by ashu16815** [microsoft/vsts-extension-retrospectives#101]
When we are trying to do Export CSV Content 
we are seeing below error on console

retrospectives.Extension launched
extmgmt.dev.azure.com/sparknz/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/3c941275-a873-4da9-b77a-4d0d77525637/Documents:1 Failed to load resource: the server responded with a status of 404 ()
reflect-bundle.js:82 Tracking event: team-retrospectives.Team changed
reflect-bundle.js:37 Uncaught (in promise) TypeError: Cannot read property 'displayName' of null
    at l (reflect-bundle.js:37)
    at e.<anonymous> (reflect-bundle.js:37)
    at reflect-bundle.js:37
![Screen Shot 2020-12-16 at 3 46 00 PM](https://user-images.githubusercontent.com/25782668/102298374-dfb8e900-3fb5-11eb-8683-311c404c2f5c.png)

    at Object.next (reflect-bundle.js:37)
    at a (reflect-bundle.js:37)

`Failed to load resource: the server responded with a status of 404 ()
reflect-bundle.js:82 Tracking event: team-retrospectives.Team changed
reflect-bundle.js:37 Uncaught (in promise) TypeError: Cannot read property 'displayName' of null
    at l (reflect-bundle.js:37)
    at e.<anonymous> (reflect-bundle.js:37)
    at reflect-bundle.js:37
    at Object.next (reflect-bundle.js:37)
    at a (reflect-bundle.js:37)`

**Comment by polatengin** [comment]
hey @ashu16815 , it seems somehow extension couldn't find the created user of at least one of the feedbacks. I made it optional to export created user. if there is a user for a feedback, added it to csv output, if not, created user for the feedback is empty.

**Comment by polatengin** [comment]
it'll be in the next flight that I plan to publish on next week
