### ISSUE TITLE
Column can't be renamed

### ISSUE THREAD

**Issue by abdullahfahmi1991** [microsoft/vsts-extension-retrospectives#103]
Cannot edit the column name.
After click Save, the new column will maintain the name as 'New column' and default columns will maintain their name too.

**Comment by toddchooch** [comment]
I was just hit from the teams about this issue.

**Comment by EricLauber** [comment]
I first noticed this 2 or 3 weeks ago and the issue is still present.

**Comment by ErikHansen1** [comment]
This is an issue our teams are having, too. I'm not sure why the customization for the column names disappeared, but not being able to rename the columns is forcing us to change the flow of our retrospectives in an unwelcome way.

**Comment by briannaritter** [comment]
Agree with all of the above - We need to be able to still add custom columns and have it save the column name.

**Comment by oliveratgithub** [comment]
See #90 : use the `Return`-key to save/apply the custom column names. But yeah, the behavior changed and is being addressed, I think

**Comment by briannaritter** [comment]
@oliveratgithub Thank you! 👍

**Comment by jluvsu2** [comment]
Ditto - we need to be able to rename or add custom columns.
