### ISSUE TITLE
Extension Removal

### ISSUE THREAD

**Issue by ArieHein** [microsoft/vsts-extension-retrospectives#11]
Ok ,so seems i was happy too soon with you guys going OSS ?

There's a message now on the extension page saying this extension is being taken off the marketplace at the end of the month.

Are all the issues we opened last 2 months not going to see the light unless its being taken over by others ?

**Comment by DibranMulder** [comment]
Yeah, I'm also very curious... Whats the story? And whats the process going to look like? Will people lose their data if it gets republished from an OSS perspective? Please give us some insights in the thinking process.

**Comment by Chris3773** [comment]
I do not see the message about taking the extension off the marketplace.

**Comment by ArieHein** [comment]
![retro](https://user-images.githubusercontent.com/15635882/81713888-bdd31300-9476-11ea-959f-b90358f37df3.jpg)

**Comment by danhellem** [comment]
We are finding a new owner for the extension within MSFT. Working on a transition now. We hope to remove that banner today
