### ISSUE TITLE
[Feature Request] Display the "retrospective prime directive"

### ISSUE THREAD

**Issue by hegold** [microsoft/vsts-extension-retrospectives#111]
It is often suggested that Norm Kerth's [retrospective prime directive](https://retrospectivewiki.org/index.php?title=The_Prime_Directive) should be read at the start of every retrospective. It would be nice to include that in this extension as a reminder, perhaps as a banner that appears at a suitable point in the workflow (e.g. after a retro is created, or when a user views a particular retro for the first time).

> Regardless of what we discover, we understand and truly believe that everyone did the best job they could, given what they knew at the time, their skills and abilities, the resources available, and the situation at hand.

**Comment by polatengin** [comment]
this is a very good feature request.

I think we can have an option in the retro board creation dialog, when that option is selected, there will be a new tab (next to Collect-Group-Vote-Act tabs) in the UI that shows the directive.

does it sound a good solution?

**Comment by hegold** [comment]
Thanks, it sounds reasonable to me! Is the idea that the new tab starts out selected, and then you can move on to the Collect tab after you read it?

**Comment by polatengin** [comment]
@hegold , yes, and since there will be a tab, anyone can return to that tab and read it, then continue where they left off. same principle as Collect-Group-Vote-Act tabs.

**Comment by hegold** [comment]
Wonderful!

**Comment by dphanson63** [comment]
I am on the opposite side of this request.  I find this adds needless clutter to the retrospective board.  I choose to flag this off, but since it defaults to on, I find that everyone of our Scrum masters leaves it on, while NEVER looking at it.

Please set the default for the Prime Directive to off.  If someone plans to use it, they'll remember to turn it on.
