### ISSUE TITLE
Cannot find my retrospective

### ISSUE THREAD

**Issue by irinelc** [microsoft/vsts-extension-retrospectives#116]
I created a retrospective and I cannot find it anymore. Was it deleted by someone? was it archived? I need the data from it so reaching out for help to recover that data

Thanks
Irinel

**Comment by polatengin** [comment]
hey @irinelc ,

Retrospective Extension uses custom data storage on Azure DevOps, all the boards, feedbacks, etc. are stored in the DevOps Organization you're using.

One can delete a board by using the "Delete retrospective" option on the UI or by calling certain Azure DevOps Rest APIs to find and delete custom data, created by extensions.

If it's deleted already, I'm not sure if you can recover it. Worth to try get the extension data by calling those Azure DevOps Rest APIs to check if the data is still there but not visible somehow.

There is a related [closed] issue; #32 , you may want to call the APIs by yourself or request help from your IT team to do that for you.

_PS : Only people who have access to your organization can do that_
