### ISSUE TITLE
Unable to rename columns on the retrospective board anymore. 

### ISSUE THREAD

**Issue by ashishdattaSPG** [microsoft/vsts-extension-retrospectives#119]
We are unable to rename the columns anymore. This was working fine untill recently and looks like a newly introduced bug. 
Repro steps:
1. Go to Edit board.
2. Rename the columns. 
3. Hit 'Save'. 
4. the pop-up closes and columns are not renamed. 
5. Refresh the board and the changes still do not appear on column name.

**Comment by marktold** [comment]
You need to click enter every time when you change the text on a column before saving.

**Comment by polatengin** [comment]
hey @ashishdattaSPG , @marktold  ,

I couldn't repro this issue, v1.0.50 (which is released couple of hours ago) should fix the requirement to hit ENTER before saving the changes.

May I ask you to double check if it's still needed?

**Comment by ashishdattaSPG** [comment]
> hey @polatengin 

Thanks for getting back. The fix is working well. I am able to Rename the columns now.
