### ISSUE TITLE
retrospectives doesn't allow us to add titles more than one letter

### ISSUE THREAD

**Issue by Vignesh257** [microsoft/vsts-extension-retrospectives#120]
Hi,

We are facing very strange issue in restropectives recently. 
This is not allowing us to add title or comment more than one  letter.
Can you please let me know if it’s just a problem on my side or if you’re experiencing the same problem? 
![Retro_error](https://user-images.githubusercontent.com/77097263/103871061-92322680-50f2-11eb-8ba3-1b6a48b8445c.PNG)

**Comment by marktold** [comment]
You can enter more but only one at the time. Currently unusable that way!

**Comment by Seuleuzeuh** [comment]
Same issue, the extension is not usable until this is fixed.

**Comment by bbo76** [comment]
Same problem here, @marktold only one at the time doesn't work anymore.

**Comment by bvmeer** [comment]
Same issue. Workaround is type your message in notepad and copy past

**Comment by Duranom** [comment]
This has happened since latest release and can only copy paste whole tekst into it

**Comment by polatengin** [comment]
oh no! let me fix it ASAP!

**Comment by polatengin** [comment]
ok, fixed. update is underway. marketplace is validating the release now. it should not take more than 2 minutes.

I am really sorry about the issue I caused!

and , as always , thanks for the feedback.

**Comment by polatengin** [comment]
marketplace validated the new release and it's installed. your organization should get this new release by now.

just checked, issue is solved.

closing this issue now, please let me know if you see any other issue.

**Comment by marktold** [comment]
Not working here, yet!

**Comment by Vignesh257** [comment]
Thanks,  issue resolved now.

**Comment by polatengin** [comment]
it may need some time to propagate to all of the organizations around the world.

can you check if you have v1.0.51 installed please?

Go to Organization Settings , Extensions , find the Retrospective Extension and check the installed version.

If you have the latest version, can you clear the cache and refresh the page please?

**Comment by marktold** [comment]
@polatengin

1) it works
2) A big thanks for the super quick fix! AAA
3) Glad to see the extension is still being developed

But the important thing here is the THANKS for the effort today!
