### ISSUE TITLE
"Only show feedback after Collect phase" not working

### ISSUE THREAD

**Issue by aconsuegra** [microsoft/vsts-extension-retrospectives#123]
Hi, I am using v1.0.51 and tested this with Chrome, Edge and Safari (MacOS).

I created a Retro board with the option to hide topics added by others during the Collect phase, but it doesn't see to be working. Everybody in the Retrospective can see topics as soon as they are added, when they are in the Collect phase. These are the settings for the board, anything I could be doing wrong?

<img width="506" alt="Screen Shot 2021-01-14 at 12 30 42 PM" src="https://user-images.githubusercontent.com/1814882/104585657-a0d58c00-5664-11eb-9b4e-860a1f16eac2.png">

**Comment by cruising** [comment]
I have the same issue in Chrome and Firefox (Windows 10)

**Comment by aconsuegra** [comment]
Any possibility to get this fixed? Or looked at?

**Comment by Segelfeldt** [comment]
We noticed the same issue last week.

**Comment by sunill-yadav** [comment]
I also noticed this issue since last couple of months. I thought I didn't understand the functionality but it turn to be an issue. Anyone is working on it?

**Comment by mindlessroman** [comment]
This should be addressed in an upcoming release!

**Comment by mindlessroman** [comment]
I believe this to be resolved at this point since it was covered in a release over the summer. Will close this for now. If something comes up again, we can explore in a new issue.
