### ISSUE TITLE
Retrospective vote feature does not work

### ISSUE THREAD

**Issue by coolkats** [microsoft/vsts-extension-retrospectives#125]
users are not able to vote on grouped feedback items. when we click up vote arrow the counter does not go up. Exported the csv file and saw that vote did not get registered.

**Comment by mindlessroman** [comment]
I think in the intervening time since this was submitted, we have addressed a few bugs related to grouping and to voting. I'll close this for now, but if behavior similar to this comes up again, we can investigate with a new issue.
