### ISSUE TITLE
[Feature Request] Creating your own template

### ISSUE THREAD

**Issue by LauritsQueueit** [microsoft/vsts-extension-retrospectives#130]
Templates are suppose to help you make your Retrospective in a fast and easy manner.
If you do not use any of these templates, you have to always change the columns, colors, and logo every time you create a new retrospective.
It would be nice if it was possible to create your own Template with the template you always use every time.

**Comment by deleister** [comment]
I agree.  When you want to standardize across time and many, many teams, templates are necessary.  Especially if you are pulling data for metrics.

**Comment by dwisnowski2** [comment]
Please add this feature!  it would be hugely helpful.   We are using this for a Scrum of Scrums meeting and I have to keep building new retro boards weekly and having to build out 6 new columns every time.

**Comment by harryjuice** [comment]
Yes!  Needed greatly!!!

**Comment by DennisvdPluijm** [comment]
Yes! Was just looking to add this wish!
For instance, we use the KALM method (Keep-Add-Less-More). It's quite similar to Start-Stop-Continue, but I need to make some changes to that template every sprint.

Another way to get a new retrospective board faster, would be to be able to copy your current board/settings to a new and clean board.

**Comment by LauritsQueueit** [comment]
> Yes! Was just looking to add this wish!
> For instance, we use the KALM method (Keep-Add-Less-More). It's quite similar to Start-Stop-Continue, but I need to make some changes to that template every sprint.
> 
> Another way to get a new retrospective board faster, would be to be able to copy your current board/settings to a new and clean board.

I actually agree that both copy board and edit, and create template would be nice.
Without knowing the architecture and the impact these make, they do sound very similar in functionality, so would perhaps hope both could come along.

**Comment by mindlessroman** [comment]
#300 is consolidating. Will close this one - follow along there!
