### ISSUE TITLE
Is there a way to limit votes per person

### ISSUE THREAD

**Issue by tbeavers** [microsoft/vsts-extension-retrospectives#131]
Is there a way to limit votes per user, so it doesn't get out of hand with everyone voting on everything, which doesn't add any value to the retrospective discussions.

For example, if each user was limited to five votes (or whatever you want to set it to), they would have to use their votes sparingly to vote on their top cards, which would provide better insight to the most important cards.

**Comment by polatengin** [comment]
yes, it's implemented with #129 

it'll be in the next release, which is planned to be out on Jan 28th.
