### ISSUE TITLE
Voting does not work at the moment

### ISSUE THREAD

**Issue by spoelly** [microsoft/vsts-extension-retrospectives#142]
When one teammember is voting all other members are getting switched to the "collect" view.
Currently only one member can vote at a time, when multiple is wat we want.

We have set the max votes set to 3 for a user.

**Comment by jeffdevalmeida** [comment]
My team haven the same problem.

**Comment by GuidoTournois** [comment]
Same issue here!

**Comment by abokov** [comment]
Voting doesn't work for this moment, almost not possible to vote at all - page focus changing to 'Collect' tab constantly

**Comment by neilkilbride** [comment]
Also experiencing the issue.

**Comment by storey247** [comment]
Ditto, and the same is happening on the "Act" tab too 😢

**Comment by mindlessroman** [comment]
Hey fokls - there have been a few voting fixes in recent releases. I'll close this for now, and we can explore any new or similar behavior in a new issue. Thanks!
