### ISSUE TITLE
Screen keeps returning to "Collect" tab

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [microsoft/vsts-extension-retrospectives#143]
While our team is in the vote tab, the screen keeps opening the collect tab. Why is this happening?

**Comment by csvdarius** [comment]
We are experiencing the same but on Azure DevOps online.  Just started recently.

**Comment by jvescio85** [comment]
during our retro/review session today, we are experiencing the same issue. Sometimes the Vote tab stays for a few seconds, other times it switches within < 1 second

**Comment by opis-mark** [comment]
Our team experienced this on Monday (2021-02-08) as well.  We seemed to think it happened to everyone on the team whenever anyone *else* on the team voted.

**Comment by BjoernTheDev** [comment]
Same issue. @opis-mark is right. Bug seems to happen when someone upvotes.

**Comment by opis-mark** [comment]
This seems to be resolved.  We're not experiencing the problem during our retro today.

**Comment by thijsvanbloemendaal** [comment]
#149  seems to be the same issue.

I'll check tomorrow if our teams are still experiencing this issue.

**Comment by thijsvanbloemendaal** [comment]
We're no longer experiencing this issue.
