### ISSUE TITLE
max vote is reinitialized each time the tab is open

### ISSUE THREAD

**Issue by tale-adents** [microsoft/vsts-extension-retrospectives#144]
If we set the maximum vote to 3, a customer can vote 3 times, then switch on collect (or redirected by the bug #142 ), when the user comes back to vote, the user current count is reset to 0 so the user can vote again 3 times.

**Comment by mindlessroman** [comment]
@tale-adents - I believe there were some voting fixes in more recent releases. Have you seen this more recently? For the time being, I'll close this issue out, and if this behavior comes up again, we can look into it with a new issue.
