### ISSUE TITLE
restrict the visibility of a team retro only for team members

### ISSUE THREAD

**Issue by rschue** [microsoft/vsts-extension-retrospectives#145]
If we have internal and external workers in a Teamproject with separate teams for different areas e.g. one for the external workers. We dont't want that the external workers see the Retro from the internal workers.

**Comment by justdait** [comment]
This is a big issue. Retrospectives should be private to the core team so they have psychological safety. Stakeholders should not be able to access the retrospective boards.

**Comment by justdait** [comment]
Could this be prioritized? In an environment where you have multiple teams working in their own product space, you want to be able to give all Product Owners access to all the different teams to help manage cross-team dependencies. However, you only want the retrospectives to be visible to the core team members. This is 101 stuff for team psychological safety. If this is not resolved teams will then use retrospective tools outwith DevOps which is counterintuitive when you are trying to develop the system to be one version of the truth.
