### ISSUE TITLE
Retrospectives Board tool in Azure Devops

### ISSUE THREAD

**Issue by Xingo123** [microsoft/vsts-extension-retrospectives#147]
Hi Microsoft devlabs

My colleagues and I did a retrospective today. It went very smoothly until we want to vote our cards. When a colleague of my upvoted a card in my screen the tab went to collect instantly. I think it’s a small bug, but I can think that people could consider it annoying.

See image

Kind Regards,

Xing Woo

![image](https://user-images.githubusercontent.com/7287730/107474405-967ab500-6b72-11eb-8a6c-81faf73a8aa4.png)

**Comment by mindlessroman** [comment]
@Xingo123 - are you still seeing this bug? There have been a few releases since you posted so I wanted to follow up.

**Comment by mindlessroman** [comment]
@Xingo123 I believe this has since been fixed with more recent releases. I'll close this for now and if new or similar behavior comes up, we can explore in a new issue.
