### ISSUE TITLE
In vote it is constantly jumping back to Collect tab

### ISSUE THREAD

**Issue by chris-eg** [microsoft/vsts-extension-retrospectives#149]
Moving through the tabs when we start voting we are finding that it is constantly jumping us back to the collect tab making voting almost impossible

This may be reated to changes being made by other people when the board refreshes it seems to take you back to collect

**Comment by harryjuice** [comment]
Yes, this is exactly what we're seeing.  This is an issue.  Please fix it!

**Comment by davidkingBG** [comment]
We are experiencing the same thing!

**Comment by charleszipp** [comment]
+1. was in a retro with 15+ people yesterday and this was occurring for everyone

**Comment by R4ffi** [comment]
Same problem here!

**Comment by mindlessroman** [comment]
Hey folks - I think this issue has since been resolved. I'll close this for now, but if new or similar behavior comes up, we can look into it with a new issue.
