### ISSUE TITLE
Re community collaborators

### ISSUE THREAD

**Issue by Kollibri** [microsoft/vsts-extension-retrospectives#16]
I'm interested in helping maintain this project in light of the current dev teams's decision to no longer support it.

How can I help?

**Comment by polatengin** [comment]
Hi @Kollibri , I'm going to own and maintain the project. I'm open to any help from community. If you're familiar with developing Azure DevOps Extensions, could you please look into open issues and start contributing from one of them?

Transitioning ownership is still on-going process, I'll update here when it completes, with more info.
