### ISSUE TITLE
Focus mode excludes grouped items

### ISSUE THREAD

**Issue by bgever** [microsoft/vsts-extension-retrospectives#165]
In Focus mode, when items have been grouped, it will only show the top item of the group, and there is no ability to see the other items in the group.

Expected behavior: the card can be expanded to show the other grouped items, similar to how this can be done on the board.

Refer to the screen shot where on the left you can see there's another item in the group, and in the focus mode that item is not displayed. Pressing the next/previous buttons do not show the hidden grouped item.

Also, note that there are 2 "more" menus, having similar functionality. Let me know if I should open a separate bug for that.

<img width="1191" alt="Screen Shot 2021-03-11 at 10 18 05 AM" src="https://user-images.githubusercontent.com/1618765/110726132-db6a3800-8253-11eb-9c32-5447e1b2f60e.png">

**Comment by mindlessroman** [comment]
Coming soon in a new release!

**Comment by mindlessroman** [comment]
This has been released! Thanks for the awesome suggestion @bgever !!

**Comment by bgever** [comment]
Thank you for the fix!
