### ISSUE TITLE
Unable to move Feedback to different columns or provide Group Feedback

### ISSUE THREAD

**Issue by fred1n** [microsoft/vsts-extension-retrospectives#169]
Project admin has the options to move **Feedback to different columns** and provide **Group Feedback** greyed out.  What permissions are need to allow this options to be enabled?

[retro-issue.docx](https://github.com/microsoft/vsts-extension-retrospectives/files/6166855/retro-issue.docx)

**Comment by mindlessroman** [comment]
Closing.
