### ISSUE TITLE
Live syncing service doesn't connect

### ISSUE THREAD

**Issue by nelson-tamayo-zas** [microsoft/vsts-extension-retrospectives#171]
From devtools console:

- POST https://retrospectivesbackendservice.azurewebsites.net/collaborationUpdates/negotiate 401 (Unauthorized) reflect-bundle.js:92
- [2021-03-25T11:55:24.508Z] Error: Failed to complete negotiation with the server: Error: Unauthorized reflect-bundle.js:23
- [2021-03-25T11:55:24.509Z] Error: Failed to start the connection: Error: Unauthorized reflect-bundle.js:35 Error when trying to start signalR connection:  Error: Unauthorized at new t (reflect-bundle.js:30) at XMLHttpRequest.e.abortSignal.e.abortSignal.aborted.e.method.e.url.o.onload (reflect-bundle.js:92)

**Comment by mindlessroman** [comment]
#293 - Using to consolidate any live syncing issues. Closing this one, and recommend following the other!
