### ISSUE TITLE
Is it possible to include feedback anonymously?

### ISSUE THREAD

**Issue by priscila-ds** [microsoft/vsts-extension-retrospectives#173]
is it possible to include feedback anonymously?
+Add a new feedback - ( but anonymously)

**Comment by b-lat** [comment]
You can turn on anonymous feedback when creating the retrospective or you can change it to anonymous by clicking the ellipsis next to the retrospective name and choosing edit retrospective.

**Comment by mindlessroman** [comment]
@priscila-ds there is a "anonymous feedback" setting during the "create retrospective" pop up, but unfortunately  you can't change that setting after creating the board.

![image](https://user-images.githubusercontent.com/7254163/168396819-72c7d5a0-e3d7-4cc6-97c9-a2edd285d3a9.png)


Closing for now, hopefully that helps.
