### ISSUE TITLE
Feature request: in focus mode, still show text of all grouped issues

### ISSUE THREAD

**Issue by allauthors** [microsoft/vsts-extension-retrospectives#176]
Focus mode is great, except when you've grouped two cards because they are topically similar/identical but each provides nuances that are needed to feed the discussion.  
It would be great if either 
A) focus mode showed grouped cards by default
B) focus mode had an option to expand grouped cards without leaving focus mode
or 
C) grouping cards automatically concatenated the subcard text onto the top card unless the text was identical (or gave a prompt asking if text should be appended).

**Comment by mindlessroman** [comment]
There is a release that should address this soon!

**Comment by mindlessroman** [comment]
This has been released! @allauthors - Thank you for the feature suggestion!
