### ISSUE TITLE
Save Retro Format Template

### ISSUE THREAD

**Issue by justdait** [microsoft/vsts-extension-retrospectives#178]
Less of a bug, more of an enhancement. As a user I would like to save a custom retro question set that can then be used across multiple teams.

**Comment by mkeresz1** [comment]
+1

**Comment by meastburn** [comment]
+1 this would be great!

**Comment by ni1402** [comment]
agree with the enhancement, I would be nice to save a template as your own.

**Comment by mindlessroman** [comment]
#300 Is consolidating these - follow along there and I'll close this one for now.
