### ISSUE TITLE
Incorrect 'delete' icon used for retro item in focus mode in DevOps Retrospectives

### ISSUE THREAD

**Issue by hibberto** [microsoft/vsts-extension-retrospectives#184]
As the title describes, the icon for ‘delete’ when viewing retros in focus mode is incorrect. It’s showing a three dotted kebab icon when it should be a delete icon. Screenshot:

![image](https://user-images.githubusercontent.com/82502718/114678575-46030d80-9d03-11eb-88c0-ba6e5216a556.png)

**Comment by polatengin** [comment]
fixed with #232

new version will not have 2 buttons
