### ISSUE TITLE
New team member cannot use Group and Act tabs

### ISSUE THREAD

**Issue by dkinsweden** [microsoft/vsts-extension-retrospectives#187]
We have a new team member who was added to the DevOps team with the same permissions as everyone else. For the new team member, the Group and Act tabs are greyed out, for everyone else it works as intended.

The Retrospectives extension was installed **before** the new team member was added, and there were previous retrospectives without them.

A new retrospective was created **after** the new team member was added, but they had the above mentioned issue.

**Comment by mindlessroman** [comment]
@dkinsweden - following up here... is this still happening?

**Comment by mindlessroman** [comment]
@dkinsweden - I'm going to close this out since it's a bit stale and there have been a few releases since this was submitted. If new or similar behavior has come up since, we can look into it with a new issue. Thanks!
