### ISSUE TITLE
Your votes are visible in Act mode

### ISSUE THREAD

**Issue by cchengt** [microsoft/vsts-extension-retrospectives#188]
Hello, in my team we usually present and go over each card in the Act phase, and we do this by screen sharing. The problem is that the votes of the presenter are shown, and this breaks anonymity. Could the Retrospectives tool have an option to hide/show the votes in the Act phase (including the Focus mode view)? Is there a workaround for this?

**Comment by dbjorge** [comment]
Yes, please!

**Comment by JGibson2019** [comment]
Would love to see this feature for increased anonymity!

**Comment by markreay** [comment]
This would be essential to using this with our team retrospectives. We place a high premium on psychological safety and honest feedback and this feature makes it difficult to use this in our retrospectives.

**Comment by mindlessroman** [comment]
Hey folks! I believe this feature has been addressed/released. "Your Votes" is not visible in the Act Phase anymore. I'll close this issue out for now, but let us know if there is still something missing.
