### ISSUE TITLE
How to compile and run this code locally on my machine.

### ISSUE THREAD

**Issue by piyushdeals** [microsoft/vsts-extension-retrospectives#19]
I want to compile the extension-retrospectives code on my machine and run it so that I can make modifications and test them. Please guide how can I do that do I need to download but the extension and backend code ?
Please guide me with the starting point of the extension.

**Comment by polatengin** [comment]
I'll prepare a DevContainer to make the development easier. Also README files should be updated with more information.

Just created a project to track the progress, this issue is in the project

**Comment by polatengin** [comment]
With the latest commits, repo now has a [DevContainer](https://github.com/polatengin/project-standards/blob/master/DevContainers.md) setup.

You can clone the repo, open it with [Visual Studio Code](https://code.visualstudio.com) . [Visual Studio Code](https://code.visualstudio.com) will detect [.devcontainer](https://github.com/microsoft/vsts-extension-retrospectives/tree/master/.devcontainer) folder and ask to open the repo in the [DevContainer](https://github.com/polatengin/project-standards/blob/master/DevContainers.md).

If you allow it, all the required tools and sdk will be inside of the [DevContainer](https://github.com/polatengin/project-standards/blob/master/DevContainers.md)
