### ISSUE TITLE
Current Sprint Retrospective is Not Loading 

### ISSUE THREAD

**Issue by JThomas77** [microsoft/vsts-extension-retrospectives#192]
Retrospective seems to have a bug where it does not load the current sprint’s retrospective.  To load the cards, you must first click on the sprint dropdown to select another sprint, then click back to the sprint you want. Is this working as designed? We believe it should open to the current sprint?

**Comment by mindlessroman** [comment]
@JThomas77 - this issue has become a bit stale and there have been a few recent releases since you first entered. I'm going to close this for now. If you're still seeing similar behavior, we can check into it with a new issue.
