### ISSUE TITLE
Retrospective feature on our site take very long to upload. Is there is a fix for this Issue?

### ISSUE THREAD

**Issue by GiselleV16** [microsoft/vsts-extension-retrospectives#199]

**Comment by mindlessroman** [comment]
@GiselleV16 - Is this an issue with the Live Syncing service? Or something else? Could you provide more details?

**Comment by mindlessroman** [comment]
@GiselleV16 - I believe some load time fixes have been deployed with a recent release. I'll close this issue for now, but we can look into any new or similar behavior in a new issue. Thanks!
