### ISSUE TITLE
Unable to load retrospectives consistently

### ISSUE THREAD

**Issue by kingkuuks** [microsoft/vsts-extension-retrospectives#234]
Retrospectives is inconsistent and I have to re-add the extension sometimes for it to load. I am not sure if it is related but I noticed a pattern of it being unable to load during busy/business hours. It mostly loads fine when traffic is low. Server has more than enough resources to handle the processes.

Is there a fix for this?
where do I access retrospectives logs?

**Comment by mindlessroman** [comment]
@kingkuuks - are you still seeing this?

**Comment by mindlessroman** [comment]
I'm going to close this for the time being, since the issue is a bit stale. If you're still seeing this with more recent releases, we can explore it more in a new issue.
