### ISSUE TITLE
Retrospectives data is missing in Migration from OnPrem to ADO Cloud

### ISSUE THREAD

**Issue by yesnaveengit** [microsoft/vsts-extension-retrospectives#239]
We had migrated collection from Onprem to ADO Cloud.

post migration installed Retrospectives in cloud but data is missing.

Could you please help me to fix it.

**Comment by yesnaveengit** [comment]
Is this extension still  supported ?

**Comment by polatengin** [comment]
hey @yesnaveengit , it's not Microsoft supported extension. It's more of a Community-Backed extension.

But I've had your issue before, let me find how did I answer the same question before and share it with you

**Comment by polatengin** [comment]
Found it ; https://github.com/microsoft/vsts-extension-retrospectives/issues/32 🥳

I'm gonna close this issue, please feel free to re-open it if you need further assistance.
