### ISSUE TITLE
Feature Request: Allow removing already cast votes

### ISSUE THREAD

**Issue by kimsey0** [microsoft/vsts-extension-retrospectives#24]
Once you've cast a vote in the Vote phase, you don't seem to be able to remove it again. Clicking an Add vote button again just adds another vote. The option to allow removing your vote could be implemented by, for example:

1. Adding a new Remove vote button besides the Add vote button
2. Adding a setting to only allow voting for each item once (related to #8), then change the Add vote button to Remove vote after voting
3. Make right-clicking the Add vote button remove votes (hard to make discoverable)

**Comment by ericbishop44** [comment]
I really like option 1. Something as simple as 

\/ 2 /\

Where the \/ and /\ are the buttons

It also would be nice to know how many votes you had cast on a given card

**Comment by polatengin** [comment]
I like the suggestion

/cc: @JankaKoen , @yayitserica

**Comment by JankaKoen** [comment]
Good idea, i will certainly have a look into it. The complexity that I see is that it would be necessary to add an indication on how many votes have I casted vs. how many votes there are in total on a particular item. Stay tuned :)

**Comment by polatengin** [comment]
this feature implemented with #107
