### ISSUE TITLE
Retrospectives will not load for certain users

### ISSUE THREAD

**Issue by JThomas77** [microsoft/vsts-extension-retrospectives#243]
We have two users where the Retrospective info will not load at all for them. I had them capture traces for reporting this issue. Who can I send them to?

**Comment by chasetilton** [comment]
Some of my team members are experiencing the same issue

**Comment by mindlessroman** [comment]
@JThomas77 - if you're still seeing this issue, if you include as much of the information here as you can - anonymizing where you need to, that would be really helpful!

**Comment by mindlessroman** [comment]
Since this issue has been a bit stale, I'm going to close it. If there is new or similar behavior that has come up in the mean time, we can explore in a new issue. Thanks!
