### ISSUE TITLE
Retrospectives is taking longer than expected to load.

### ISSUE THREAD

**Issue by cematza** [microsoft/vsts-extension-retrospectives#245]
Retrospectives often fails to load for many users.  Sometimes removing and reinstalling the extension will overcome, but not always.  At other times, it will load w/o intervention.  Seems to be no discernable pattern.  We have analyzed server resources & done network traces thru firewalls, and haven't uncovered any cause for this.  Are there any recommendations for addressing this?  

We really like the functionality and want to continue to use.  But it currently fails to load too often and at times when we can least tolerate it.

**Comment by pbcahill** [comment]
We get this issue too, in both Azure DevOps Services and on-prem Azure DevOps Server instances. No discernable pattern or resolution for us either. Get complaints from many different teams across our org about this.

**Comment by wadedevops** [comment]
Also want to add that we experience that too on a number of different DevOps instances.
Our users are getting very frustrated with it and find it's a little better using Edge, but still struggle.
Would be great to get feedback from DevLabs as to if/when they going to get a fix out for this.
I'm guessing it's probably using an old SDK, which has UI performance issues. Maybe if they upgraded the SDK it's developed on it would help ?
