### ISSUE TITLE
extension doesn't honor users' theme selection

### ISSUE THREAD

**Issue by polatengin** [microsoft/vsts-extension-retrospectives#25]
Extension should honor users' theme selection.

It should be dark if user chose dark theme, light, if user chose light theme, etc.

My understanding is, in the `main.scss` file we need to have reference to `_platformCommon.scss` file

**References**
* [Extension development](https://developer.microsoft.com/en-us/azure-devops/develop/extensions)
* [Styles](https://developer.microsoft.com/en-us/azure-devops/develop/styles)
* [Sample Web Extension for Azure DevOps](https://github.com/Microsoft/azure-devops-extension-sample)

**Comment by mpth** [comment]
As this extension uses the old vss web extension SDK the links you shared will not necessarily help us. 

There is an undocumented option in the old extension SDK that could potentially work. I haven't used it myself but it should inject the current themes CSS variables into the extension iframe.

https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/vss/references/vss_sdk_interfaces/iextensioninitializationoptions (see comments)

Only found this blog post in German that explains how it works :-) 
https://www.aitgmbh.de/blog/tfs-devops/theme-unterstuetzung-fuer-azure-devops-erweiterungen/

Switching to the new SDK is only an option if we can drop support for Azure DevOps Server versions that dont support the new SDK. I dont know what version that is but I'm sure we can find out.

**Comment by polatengin** [comment]
I think we can drop old Azure DevOps Server versions in favor to have newest and greatest features.

I didn't do that before, is it as simple as bumping dependency version in package.json or should we change codes in files as-well? Did you do that before?

**Comment by mpth** [comment]
This would mean we would lock out folks from updates that are currently using it with TFS Server 2018 Update 2/3. I'm all for it - just making sure this is clear.

![grafik](https://user-images.githubusercontent.com/58585371/82999696-afa1fc80-a009-11ea-88f3-d7bdfab9aabd.png)

The Estimate extension by @cschleiden targets both Azure DevOps Services and Azure DevOps server and uses the new SDK with theming support. Maybe he has some advice :)

**Comment by mpth** [comment]
Maybe we can try using the applyTheme initialization option first before thinking about switching out the SDK.

https://github.com/microsoft/vss-web-extension-sdk/pull/105

**Comment by polatengin** [comment]
it may solve this issue very quickly and easily 😊

I can test it out this weekend

**Comment by yayitserica** [comment]
@jankakoen will make color suggestions to @polatengin

**Comment by mindlessroman** [comment]
I believe most of the theme issues have been addressed. Worth closing @polatengin ?

**Comment by polatengin** [comment]
I'm closing this issue since "I think" all the theming issues addressed 👍
