### ISSUE TITLE
convert tslinter to eslinter

### ISSUE THREAD

**Issue by polatengin** [microsoft/vsts-extension-retrospectives#27]
In the Frontend project, tslint is used as the linter.

According to the official page [TSLint GitHub Repo](https://github.com/palantir/tslint) TSLint is deprecated and advised to use [ESLint](https://eslint.org/) instead.

We need to remove TSLint and related dependencies, TSLint rules, etc. and create a good set of rules for ESLint.

**Comment by mpth** [comment]
Happy to pitch in. I would also recommend adding [lint-staged](https://github.com/okonet/lint-staged/blob/master/README.md) - happy to do it as well.

**Comment by polatengin** [comment]
thanks for offering help @mpth , please go ahead and implement 👍

**Comment by polatengin** [comment]
since @mpth s PR is merged, I'm closing this issue.
