### ISSUE TITLE
Need option to Create Retro Template and / or Clone as New

### ISSUE THREAD

**Issue by robbiesmith79** [microsoft/vsts-extension-retrospectives#270]
Yes I know there's a comment to create a retro template, but I'm also voicing my opinion that this would be a great addition to the Retrospectives section. I would love to be able to create my own Retrospective templates or take an existing one and clone as new without the retrospective items. 

Thank you.

**Comment by Minna-jabra** [comment]
Yes please - we need this. We need to be able to create our own Retrospective templates or take an existing one and clone as new without the retrospective items.

**Comment by mindlessroman** [comment]
#300 is consolidating... Will close here, and recommend folks follow along there!
