### ISSUE TITLE
Extension installed, but just displays a blank screen

### ISSUE THREAD

**Issue by GraemeMalcolm** [microsoft/vsts-extension-retrospectives#274]
I've installed the extension, but it just shows a blank screen. Any ideas?
![image](https://user-images.githubusercontent.com/11771134/136806317-cccec959-3a8a-415c-8ceb-155cb0798628.png)

**Comment by ryanpfalz** [comment]
+1 Also having this issue.

**Comment by polatengin** [comment]
ah, this is super strange. let me look it up and fix the problem. sorry for inconvenience.

**Comment by jagruar** [comment]
Same issue and same errors as Thumper369

**Comment by Rus1an31** [comment]
+1
The same issue and errors in Console in browser

**Comment by davidrichardwillis** [comment]
Same issue for us.  It is very inconsistent.  I can't bring up the Retro board for one project but I can for others.  But I consistently can't open the same project's Retro Board.  Others can open the board that I can't, but they have issues opening other project's Retro Boards that I can open.

**Comment by mkArtakMSFT** [comment]
+1 several leads are facing this in our team (ASP.NET)

**Comment by jovencastillo** [comment]
We also have this issue for Retrospective installed in Azure DevOps

**Comment by BertrandMuhire** [comment]
Having a similar issue. The page is blank when I try to access the Retrospective board for the first time. Any idea when this will be fixed?

**Comment by mkArtakMSFT** [comment]
And @polatengin just fixed it, and it's working for me!
**THANKS @polatengin** !

**Comment by GraemeMalcolm** [comment]
The issue appears to be fixed for me in the latest release (1.60.7) (thanks @polatengin!)

**Comment by polatengin** [comment]
so sorry for the inconvenience folks.

I fixed the issue and as @GraemeMalcolm and @mkArtakMSFT stated released a new version (1.60.7)

if you refresh the page, the extension will reload.

closing the issue now, please feel free to re-open it, if you still have the issue.

**Comment by gsd90** [comment]
We are having the exact same issue and behabving very randomly on the latest version. can you please check.
