### ISSUE TITLE
Retrospectives board won't load

### ISSUE THREAD

**Issue by lisanickel383** [microsoft/vsts-extension-retrospectives#275]
I am  unable to load the retrospectives board - there is either an error message stating the page is taking a while to load or it presents with a blank white screen. Thanks!

**Comment by fd0cwp** [comment]
Same in our company. Some Retros show up, for other teams, the screen just stays empty.

**Comment by pravula** [comment]
We are facing the issue this morning as well. Restrospective board wont load for some team projects.

**Comment by srivaranasi** [comment]
@polatengin, Thanks a lot it's working now.
