### ISSUE TITLE
New Template Option

### ISSUE THREAD

**Issue by Shauly12** [microsoft/vsts-extension-retrospectives#281]
Is it possible to have a template option with the following columns?

1)	{Megaphone} “Shout Outs”
2)	{Smiley Face}  “Went Well”
3)	{Sad Face} “Didn’t go so Well”
4)	{You Pick Icon} “Blockers”

**Comment by afroze9** [comment]
Would like to add to this. Would it be possible to add a Settings Page where the templates can be customized?

**Comment by mindlessroman** [comment]
#300 is consolidating these. Closing for now - follow along there!
