### ISSUE TITLE
Unable to see Measure Team Effective in Retrospective Plugin

### ISSUE THREAD

**Issue by rasmuskaae** [microsoft/vsts-extension-retrospectives#282]
After the latest update I am seeing a Measure Team Effectiveness tab in the Retrospectives plugin. This is nice, however there is no way of seeing the results of the survey.

**Comment by BCOps** [comment]
Confirmed as per @rasmuskaae feedback - Added to a retrospective board and collected some responses, but cannot find a way to see results or find information in release notes relating to the feature.

**Comment by ToyaPreston** [comment]
Agree with all of the above. Is there an ETA on when this will be fixed?

**Comment by jwedel** [comment]
Same here. I really like this feature and also the questions are much better than the regular weather report. But without being able to view it, it pretty useless.

**Comment by jwedel** [comment]
OK, I've searched the sources and found a new PR just merged a couple of days ago: https://github.com/microsoft/vsts-extension-retrospectives/pull/285

It is now working rudimentary. 
- It saves now the selected radio button state for each user (was also not working before)
- You can go to meatballs menu -> "Show retrospective summary" -> "Effectiveness scores"

Nice to see some development here. 

Now you might want to vote on that one :) : https://github.com/microsoft/vsts-extension-retrospectives/discussions/284

**Comment by jwedel** [comment]
Aaand another little downer, the Retrospective summary seems to only show your personal scores, not the team average. I also recognizes, that the scores I did yesterday, disappeared today. So its not very helpful yet. But as I see constant development here, I am hopeful that this will improve, soon!

**Comment by crh225** [comment]
![image](https://user-images.githubusercontent.com/19475195/142279440-f33fc03a-f7ae-48c1-a33f-6dd09ef58c22.png)
I think it has some bugs still. We didnt create any action items at all and it says we made 6. Zero participants contributed and it says three did. I got a person not in this group of three to submit on the team effectiveness and none of their scores showed up.

**Comment by Dadsh** [comment]
Refresh the web page, and it works (for me)!

**Comment by cam-smith** [comment]
Seems I had to completely close and reopen the page to get average scores from the team, not just my own.

**Comment by Marius-du-Toit** [comment]
It would be nice if you could show the total # of responses for "Effectiveness Scores".

**Comment by dstoddar** [comment]
@Marius-du-Toit , the new version will include this!

**Comment by melvingiovanniperez** [comment]
I've noticed that the participants contributed count does not change regardless of how many people participated in the Retrospective and how many votes occurred. Does that number track the number of participants or the number of people who took the Measure Team Effectiveness survey?

![image](https://user-images.githubusercontent.com/64896520/172247797-821a8f49-6ede-40c3-ac7c-947ca09040ed.png)

**Comment by souldevops** [comment]
The results are visible in "Show retrospective summary" right next to Sprint name
![image](https://user-images.githubusercontent.com/132064688/235136596-bf2ad1bd-16df-4c96-9839-92c02f2c2c66.png)
