### ISSUE TITLE
Option to Group/Filter by Feedback Author

### ISSUE THREAD

**Issue by deepeshmehta4u** [microsoft/vsts-extension-retrospectives#288]
### Discussed in https://github.com/microsoft/vsts-extension-retrospectives/discussions/110

<div type='discussions-op-text'>

<sup>Originally posted by **polatengin** December 31, 2020</sup>
👋 Welcome!
---
We’re using Discussions as a place to connect with other users of the extension.

We hope that you:

* Ask questions you're wondering about.
* Share ideas.
* Engage with other users.
* Welcome others and are open-minded.

Remember that this is an extension we build together 💪.</div>

**Comment by mindlessroman** [comment]
from @deepeshmehta4u's title originally:  I'm unable to group the multiple feedbacks added by any individual in Retrospectives. Currently, it has the option to group the feedback using feedback Title only. It would be a useful feature to group the feedback using individual's name as well in Retrospectives.

**Comment by mindlessroman** [comment]
#327 - Consolidating under this issue for now.
