### ISSUE TITLE
Port number is not part of the generated retrospective link

### ISSUE THREAD

**Issue by bgotowal** [microsoft/vsts-extension-retrospectives#29]
In Retrospectives view in Azure DevOps (Boards -> Retrospective), when clicking "Copy retrospective link" button in the specific retrospective's menu, I got my URL copied but without PORT where Azure DevOps is hosted (on prem version).

E.g.
Current: https://{server}/{org_name}/{project_name}/_apps/hub/ms-devlabs.team-retrospectives.home...
Expected: https://{server}:**{PORT_NUMBER}**/{org_name}/{project_name}/_apps/hub/ms-devlabs.team-retrospectives.home...

Port number is not currently shown when generating a link what makes entire link invalid if app is hosted not under default ports (e.g. 443).

Version Dev17.M153.5

**Comment by polatengin** [comment]
thanks for reporting this, extension's already redirecting to latest board, may I ask for what scenarios are you copying url?

**Comment by bgotowal** [comment]
Two use cases:
1. If you have multiple teams created in azure devops, the default view might not be in your team. For convenience, we would send out a specific link prior to the meeting.
2. when sending out a summary post meeting or referring to previous retrospectives, we would like to send/store a link to the specific instance in time.

**Comment by yayitserica** [comment]
@polatengin is testing this and will close.

**Comment by polatengin** [comment]
port number added to generated retro link with PR #72
