### ISSUE TITLE
Team effectiveness survey does not work, no value whatsoever 

### ISSUE THREAD

**Issue by justdait** [microsoft/vsts-extension-retrospectives#292]
You capture your score and save but then there is no way to see the average score between the team.

**Comment by justdait** [comment]
Worked out how to get the average score but it was not intuitive. When I looked the show retro summary before it just gave my score but you need to get the team to log out of the retro for it to create a summary with average scores.

**Comment by polatengin** [comment]
hi @justdait , you're totally right to say that, please let me explain;

I'm building the extension myself and it's my side project. as you can imagine, it takes time..

honestly, sometimes I start building a feature, without thinking thoroughly about reporting, though it's not the case with team effectiveness survey feature.

most probably, I'll work on reporting part of this feature more, but it'll take time 😄

please keep using the extension and let me know if you have any future suggestions or ideas about improving the extension.

you can't imagine how it makes my work easier 👍


bests,
engin.
