### ISSUE TITLE
Team member unable to connect the live syncing service

### ISSUE THREAD

**Issue by GabrielaRMenezes** [microsoft/vsts-extension-retrospectives#293]
Team member unable to connect the live syncing service. He´s getting this error for many days and this error do not disappear, what doesn´t allow him to contribute with squad event. 
ID: abhijit.ghorad-ext@ab-inbev.com
Retrospective board link: https://ab-inbev.visualstudio.com/Tech%20Supply/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=90913574-2e68-42ef-b089-40b52c7685b7&boardId=0d3d6212-5804-4017-83e7-7e116bc06cdf

![Retro error](https://user-images.githubusercontent.com/95290092/144049681-b17d8fc3-ac72-41ab-9aaf-a1638edf56b1.PNG)

![image](https://user-images.githubusercontent.com/95290092/144049579-37d12158-bc6d-401e-97ef-e1ae265772e0.png)

**Comment by mindlessroman** [comment]
Hey folks - There have been a few releases since this was first entered and I believe a few worked to resolve the loading issue. I'll complete this for now, but if you see new or similar behavior, we can explore in a new issue. Thanks!
