### ISSUE TITLE
When typing the work item ID to look up a work item, it loses focus on every character

### ISSUE THREAD

**Issue by trajano** [microsoft/vsts-extension-retrospectives#295]
When typing the work item ID to look up a work item, it loses focus on every character.  My presumption is you're doing a state change on the whole component that includes the field.

https://stackoverflow.com/questions/42573017/in-react-es6-why-does-the-input-field-lose-focus-after-typing-a-character

**Comment by polatengin** [comment]
hi @trajano , this issue was solved in one of the older PRs.

may I kindly ask you to double check if you still have the issue or if it's solved, please?

closing this issue for now, re-open if the issue persists 👍
