### ISSUE TITLE
AzureBoard Retro extension

### ISSUE THREAD

**Issue by jpawelczak** [microsoft/vsts-extension-retrospectives#296]
When entering Retrospective, I see "Retrospectives" tab and nothing else.

**Comment by mindlessroman** [comment]
@jpawelczak - Could you provide more details here if you're still having troubles? A screenshot would be good to see what you're seeing.

**Comment by mindlessroman** [comment]
Since this is a little stale, I'll close this for now. @jpawelczak, if something like this has occurred in more recent releases, we can explore in a new issue. Thanks!
