### ISSUE TITLE
Screen Readers

### ISSUE THREAD

**Issue by karenmcinrueTR** [microsoft/vsts-extension-retrospectives#297]
Anyone know how if retrospectives work with screen readers for accessibility issues?

**Comment by polatengin** [comment]
hi @karenmcinrueTR , did you able to use the extension with a screen reader? I spent good amount of time to make the extension screen reader friendly, if you notice anything that causes accessibility issue, please let me know 👍

closing this issue for now, please re-open it if you need further help.
