### ISSUE TITLE
How can I save my own retro board template

### ISSUE THREAD

**Issue by wangmeng6945** [microsoft/vsts-extension-retrospectives#298]

**Comment by nisancigokmen** [comment]
?

**Comment by wangmeng6945** [comment]
I mean when I want to create a new retro, it has some template for me to select, however I want to use my own template, how can I save my current template and make it for next use??

**Comment by nisancigokmen** [comment]
by cloning the link.Gökmen.
-------- Orijinal mesaj --------Kimden: wangmeng6945 ***@***.***> Tarih: 22.12.2021  11:52  (GMT+03:00) Alıcı: microsoft/vsts-extension-retrospectives ***@***.***> Cc: Gökmen Nişancı ***@***.***>, Comment ***@***.***> Konu: Re: [microsoft/vsts-extension-retrospectives] How can I save my own retro board template (Issue #298) 
I mean when I want to create a new retro, it has some template for me to select, however I want to use my own template, how can I save my current template and make it for next use??

**Comment by nisancigokmen** [comment]
unfortunately i couldn't understand :=(

**Comment by allnerag** [comment]
Hi, it is to be able to create a new Retrospective Board, there is an option to apply a template.  How can we create our own template to use? Not create a manual one. Example, having a template called "Good-Bad-Planned-Recognition". You would be able to et the color and Icons as well. It is very time consuming to create the boards manually.  Currently working with about 14x companies where we have to create new boards every week manually. It is a real pain.

**Comment by ez-ms** [comment]
Hey @allnerag, check out this extension because I think it does what you need. Even if not, it is being actively maintained and new features are being developed quite quickly, so you can always get in touch with their team and check what are the options: https://marketplace.visualstudio.com/items?itemName=appgami.appgami-retrospectives

**Comment by mindlessroman** [comment]
Closing this in favor of the consolidated #300 - follow along there.
