### ISSUE TITLE
[Feature Request] Create/Save New Board Templates for Re-use across Organization/Project/Team

### ISSUE THREAD

**Issue by afroze9** [microsoft/vsts-extension-retrospectives#300]
Consolidating all requests regarding "Create/Save New Board Templates for Reuse". These are the issues that are currently open and have similar ideas:
* #88 by @oliveratgithub
* #130 by @LauritsQueueit
* #178 by @justdait
* #270 by @robbiesmith79
* #281 by @Shauly12
* #298 by @wangmeng6945

Points of interest:
* @oliveratgithub in #88 would like the templates to be stored at team level
* @justdait in #178 would like templates to be usable across multiple teams
* I personally think the ability to save templates should be available at team/project/organization levels (this was the use case I came searching for in the first place)

Going through the code, I can see that currently the data for templates is stored in a list inside `FeedbackBoardMetadataForm` which is then passed over to the parent container to be saved.

I propose the following changes:
1. Create a settings page that allows users to create/clone templates and save them at either the organization, the project, or the team level. The templates will be saved using the `ExtensionDataService`.
2. Load the list of templates based on current project/team (as well as all organization level templates) into the template selection dropdown.

If this sounds good and no one else is working on it, I would like to give it a shot.

**Comment by nisancigokmen** [comment]
?

**Comment by ThatKasper** [comment]
Eagerly awaiting a feature where we can create our own template, or at the very least copy a board we've already set up to use for our recurring bi-weekly Retros. I'm in a large organization with multiple teams on our SAFe ART that are also very interested in having this ability. Massive time (and sanity) saver!

**Comment by dsczltch** [comment]
We are also looking to create our own templates or to keep the same columns as the previous retro.

**Comment by jeanplevesque** [comment]
This would save so much time!

**Comment by timurkaripov** [comment]
Any plans/updates with this?

**Comment by iniemienie** [comment]
We have the same request within our company, so I'm also very curious in when this feature is planned?  Or if there are workarounds with APIs to automate the process ourselves

**Comment by mananpatel26** [comment]
+1 to that. It will be nice to add custom template for retro.

**Comment by JStuve** [comment]
Resolved with #561 

Further discussion on template saving will be address in a future discussion.
