### ISSUE TITLE
How/where can I see team effectiveness features answers

### ISSUE THREAD

**Issue by raji-nallan** [microsoft/vsts-extension-retrospectives#302]
i am struggling to find out the answers given by my team in the retro for team effectiveness feature. Can someone help me?

**Comment by nisancigokmen** [comment]
How can I help you?
,Gökmen.

**Comment by raji-nallan** [comment]
I have used the team effectiveness feature in retrospective. All my team has participated and answered those questions. I cannot find the votes/graph for the answers that my team has selected. 
where can I view them?

**Comment by nisancigokmen** [comment]
What exactly was the theme of the event? maybe i can help if i know the topic.

**Comment by raji-nallan** [comment]
I have mentioned it in my initial statement. It’s retrospective extension. I was using that extension to conduct retrospective with my team & used that new feature -“Team effectiveness Measure”.
All my team have voted for the questions in the new feature but I can’t seem to find what did they choose and where is the feedback saved

**Comment by nisancigokmen** [comment]
It may have been deleted because it is out of date, my friend, sorry. recreate it. Is there anything else I can help with? :bear:

**Comment by raji-nallan** [comment]
Is “Measure team effectiveness” feature out of date?

**Comment by polatengin** [comment]
hi @raji-nallan ,

"Measure Team Effectiveness" feature's not out of date. in fact, it's still under development and improvement.

You can find the results under the "Show Retrospective Summary" menu item.

You can reach the menu item from the triple dot button (...) next to the current retrospective session name dropdown

![image](https://user-images.githubusercontent.com/118744/148653128-8d79d64a-8a6e-42fa-99e4-baf7921f2c85.png)

**Comment by polatengin** [comment]
a quick message to @nisancigokmen, please make sure you're sending correct messages and try not to create confusion, thanks.

**Comment by raji-nallan** [comment]
Ah, silly me! I missed looking into it. I explored everything except that summary option. 
Thank you for resolving my query!

**Comment by tomRedox** [comment]
It's worth knowing that you need to refresh the page after everyone has completed their survey for the averaged scores to be shown, otherwise you'll just see your own scores.
