### ISSUE TITLE
Please show time in appropriate format rather than always seconds

### ISSUE THREAD

**Issue by hegold** [microsoft/vsts-extension-retrospectives#305]
When "act" time exceeds 60 seconds it would be nice to have the elapsed time display in minutes and seconds rather than seconds.

**Comment by polatengin** [comment]
it's a great suggestion. I'll add it to backlog of v2 👍

**Comment by mindlessroman** [comment]
This should be addressed in a release soon!

**Comment by mindlessroman** [comment]
This is live! Thank you for the suggestion @hegold
