### ISSUE TITLE
confusing alignment of checkboxes

### ISSUE THREAD

**Issue by DougDeden** [microsoft/vsts-extension-retrospectives#308]
The alignment of the checkboxes for Create New Retrospective is confusing.  The "Make all feedback anonymous" checkbox being indented beneath the "Include Team Effectiveness Measurement" checkbox implies that the former is a child item of the latter, and would affect the anonymity of the Team Effectiveness measures. But it's probably just an artifact of them all being centered. Unless there is a compelling reason to center them, they should be left-aligned, to avoid such ambiguity.

![image](https://user-images.githubusercontent.com/98361834/150878273-3cfda1a9-d7dc-4ebb-a11c-418aa7d16e97.png)

**Comment by polatengin** [comment]
I think it's time for us to visit `Create new retrospective` popup and re-style it

**Comment by mindlessroman** [comment]
This should be addressed in a release soon!

**Comment by mindlessroman** [comment]
This has been released! The alignment is now left-justified instead of center-justified.
