### ISSUE TITLE
move to new sdk

### ISSUE THREAD

**Issue by polatengin** [microsoft/vsts-extension-retrospectives#31]
Retrospective Extension still uses VSS.SDK, which is too old. It's from Visual Studio Team Services times, before Azure DevOps.

New SDK provides better performance, theming, UI controls, etc.

There is a guide to upgrade older SDKs to new one;

[Extension development](https://developer.microsoft.com/en-us/azure-devops/develop/extensions)

**Comment by yayitserica** [comment]
Thanks @polatengin !

**Comment by thomasvdb** [comment]
@polatengin The guide you're referring to does not really has an upgrade guide as far as I can see and I can't find any other documentation about it.

I'm willing to invest some time to accomplish this but it seems you need to do a complete rewrite of the app.
Do you have any guidelines/pointers for such an upgrade?

**Comment by polatengin** [comment]
hey @thomasvdb , I prepared following list to myself , I think it's valid, what you think?

* remove the old SDK reference from [package.json](https://github.com/microsoft/vsts-extension-retrospectives/blob/master/RetrospectiveExtension.Frontend/package.json)
* add new SDK to the [package.json](https://github.com/microsoft/vsts-extension-retrospectives/blob/master/RetrospectiveExtension.Frontend/package.json)
* do required modification in the [sample-hub.html](https://github.com/microsoft/vsts-extension-retrospectives/blob/master/RetrospectiveExtension.Frontend/src/sample-hub.html)
* check if reference in the [index.tsx](https://github.com/microsoft/vsts-extension-retrospectives/blob/master/RetrospectiveExtension.Frontend/index.tsx) is still valid
* search for _VSS_ in the codebase, do the required modification, if needed
* test everything 😄
* create a PR

**Comment by thomasvdb** [comment]
@polatengin I have the same list actually 😄  But step 5 is the most difficult as it's not easy to find the corresponding API from VSS.SDK in the new SDK.

An overview between the two SDK's would be helpful. If not available, it will be trial and error.

**Comment by polatengin** [comment]
hmm, I haven't done upgrading SDK before. if I understand it correctly, whole SDK is only 2 files (https://github.com/microsoft/azure-devops-extension-sdk/tree/master/src) and I found full reference on this page (https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-sdk/)

but you're right, it could harder and more messy than I first thought.

do you want to do pair programming with me? if we both attack, I'm sure it won't hold long and we can tackle it 😄
