### ISSUE TITLE
 Retrospective data is not loading after migration to cloud

### ISSUE THREAD

**Issue by deepuhnb** [microsoft/vsts-extension-retrospectives#311]
I am migrating the collection from ADO on-premise to ADO SAAS. The retrospective data is not loading after the collection is successfully migrated. I have lots of boards where retrospectives are created in the on-premise collection, which are not showing up in the migrated organization.

Please let me know if there is any workaround to export and import the retrospective data to SAAS organization.

Migration is performed using the Azure SQL VM Migration approach using the latest version of the Microsoft migration tool.

**Comment by polatengin** [comment]
hi @deepuhnb,

same problem was handled in this closed issue; #32 

I heard several people used this guide to move data from on-prem to hosted Azure instance.

closing this ticket for now, please let me know if you have any issue or need further assistance.

**Comment by deepuhnb** [comment]
Thanks much for quick response. Thanks
