### ISSUE TITLE
Moving from on-prem to services we lost all data

### ISSUE THREAD

**Issue by tegaaa** [microsoft/vsts-extension-retrospectives#32]
Hey guys, is there a way to reattach the data from an on-prem instance we moved to the cloud my customer would really love to have access to their historical retros.

Thanks,
Etiennne

**Comment by polatengin** [comment]
Hi @tegaaa let me check with the team, qq: what is on-prem instance version? (Azure DevOps Server 2019 hopefully?) I hope I can give happy news 😃

**Comment by tegaaa** [comment]
Yes it is 2019 1.1

**Comment by polatengin** [comment]
ok, I'll look into it and let you know when I have an answer.

thanks for reporting this.

**Comment by tegaaa** [comment]
Awesome we look forward to your answer!!

Thanks Engin,

ET

**Comment by polatengin** [comment]
I asked a contact internally to redirect this question, when I have the answer, I'll update here.

**Comment by tegaaa** [comment]
Excellent thanks Engin!
________________________________

**Comment by mpth** [comment]
@tegaaa you should be able can get your retrospectives data out of the old instance with REST api calls to

`all boards of a team -> https://extmgmt.dev.azure.com/your-org/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/<team-id>/Documents` 

`all cards of a retro board -> https://extmgmt.dev.azure.com/your-org/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/<board-id>/Documents` 

I don't know how the host / base url looks like on-prem but you can easily figure that out by looking at the network tab in your browser dev tools.

To re-create the boards and cards you just issue `POST` requests to the same URLs accordingly.

**Comment by tegaaa** [comment]
I got all the shinny things 😉.  All is good now no triangle and here is the battery picture in Vantage
[A picture containing clock  Description automatically generated]
I suppose 170W is not an issue right? I only had a 135W plugged before.

Thanks for you awesome service!! I will recommend Lenovo to my colleagues.

Cheers,
ET

**Comment by tegaaa** [comment]
Wow this is great.  We’ll give it a try and circle back.

Thanks for your help Michael.

Cheers,
ET

**Comment by polatengin** [comment]
I was suggested to loop through on-prem data and send it to cloud using Rest Apis too. ([ExtensionManagementRestClient class](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/extensionmanagementrestclient?view=azdevops-ext-latest))

I hope it'll solve your problem.

I'm closing this issue for now, please feel free to reopen in case of more related questions.
