### ISSUE TITLE
retrospective board is not coming good

### ISSUE THREAD

**Issue by shubhamsaurav14** [microsoft/vsts-extension-retrospectives#322]
i am not getting a board view, and i am also not getting option to create new retro, neither option to change view. i need a quick fix.

![image](https://user-images.githubusercontent.com/40036344/156703548-bde0fd2c-d32d-4099-aa92-f0a4637b67f3.png)

**Comment by mindlessroman** [comment]
This may be if your window size is smaller, the design appears mobile.

**Comment by mindlessroman** [comment]
@shubhamsaurav14 - this should be resolved with making your window larger. Closing for now, but do reopen if that doesn't resolve this issue.
