### ISSUE TITLE
Feature Request: Retrospective cards that visually display id numbers

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/vsts-extension-retrospectives#33]
As a user participating in a retrospective, I would like to be able to verbally identify retrospective cards by their id numbers. This would facilitate the conversation that unfolds when voting on and grouping cards as a team. As a remote online participant of a retrospective, id numbers would provide a way for me to more readily group cards into a set of categories that I would like to share.

**Comment by polatengin** [comment]
I like the idea. I'm currently working with a group to overhaul the UI and UX of the extension. This should be discussed indeed. Thanks for reporting this.

When I have more information about what comes when and how, I'll update here.

**Comment by mindlessroman** [comment]
I believe this has been implemented since this issue was created! Closing for now.

**Comment by raydixon** [comment]
@mindlessroman should items in existing retrospectives have/display IDs or only those created after updating to the build with this feature implemented?
