### ISSUE TITLE
Where's the Measure Team Effectiveness result?

### ISSUE THREAD

**Issue by teejax** [microsoft/vsts-extension-retrospectives#332]
Hello,
Good job with the extension!
How do we see the result of the "Measure Team Effectiveness" feature?
I have been looking for that.
Thanks

**Comment by DanTheManPearson** [comment]
From the three dots next to the retrospective name you can select "show retrospective summary" from the dropdown. Refresh first, just to make sure you capture everything that was entered.

**Comment by polatengin** [comment]
duplicate to the #336
