### ISSUE TITLE
Retrospective addin keeps loading and never loads

### ISSUE THREAD

**Issue by prematiwari** [microsoft/vsts-extension-retrospectives#333]
Hi Team,

Is there any fix provided for the issue where retro addin keeps loading. This is a very cool addon but unable to use it effectively while in retrospective calls as its not loaded for all team members

IS there any limitation ?

**Comment by mindlessroman** [comment]
@prematiwari - Could you provide a bit more context? Is this on-premises or remote? There have been a few recent releases that may hhave addressed this since you entered. Let us know if it's still occurring.
