### ISSUE TITLE
Survey results for "Measure Team Effectiveness"

### ISSUE THREAD

**Issue by abner2022** [microsoft/vsts-extension-retrospectives#336]
Our team filled out the "Measure Team Effectiveness" survey, but we can not find the results.
I have clicked and checked every possible option on the ADO extension for Retrospectives, but still can not find the results.
Can you guide me to finding those?
Thanks!!

**Comment by mvpm92** [comment]
@abner2022 I'm currently experiencing this same problem..  Would love to know how to find it!

**Comment by dmuci2022** [comment]
Same!

**Comment by SquGus** [comment]
+1 on the other users having this issue.

**Comment by SalmaHanafi** [comment]
Hi! If you click on the three dots beside the board name and go to "Show Retrospective Summary" it should show the average scores for the survey.
![image](https://user-images.githubusercontent.com/48526268/167216528-e42a98b3-6806-421f-b0b4-cc5ff4941297.png)

**Comment by abner2022** [comment]
Thank you!!!

**Comment by polatengin** [comment]
we'll have extended summary for the team effectiveness in the next release, hope you'll enjoy it

![image](https://user-images.githubusercontent.com/118744/167307109-a14e4edb-9513-4711-acef-08df367baa4d.png)
