### ISSUE TITLE
Bookmarkable and shareable link of a retrospective  

### ISSUE THREAD

**Issue by mukeshkagarwal** [microsoft/vsts-extension-retrospectives#337]
As a scrum master I need a easy way to share link of a particular retrospective to the team or outside. 

URL in the browser should be bookmarkable.

Currently the link is hidden under a menu

**Comment by polatengin** [comment]
hey @mukeshkagarwal , you can use `Copy Retrospective Link` menu item in the three dot menu (...) next to the board selection dropdown.

that link loads the selected board
