### ISSUE TITLE
Restriction and also removal of Votes , Add a timer

### ISSUE THREAD

**Issue by Nikki-na** [microsoft/vsts-extension-retrospectives#34]
Be able to configure how many votes per person 
So each person has say 5 votes each
Plus being able to remove a vote if a vote has been made in error
​

So one person can put all their votes on either one card (if they feel strongly about it)
​or allocate the 5 out how they wish
​Sounds good to have something in the config
​

that's how other similar online retro tools work
​if I have more ppl attending then I may limit them to 3 each
​if less ppl then maybe 5 each etc
​but definitely one person should be able to allocate their votes just how they wish so against either one or however many they choose
​plus being able to remove a vote is quite important 
 
Add in a timer then that would also be awesome

**Comment by yayitserica** [comment]
I will split out the "timer" ASK into a new issue, will link here.  Pending an investigation, we will determine if it should be in 1.5.

**Comment by Nikki-na** [comment]
Okk that would be alright, please go ahead.

**Comment by yayitserica** [comment]
Linked to #44

**Comment by polatengin** [comment]
uncasting vote is implemented with PR #107

timer feature request is linked to #44
