### ISSUE TITLE
Access issue on vsts-extension-retrospectives

### ISSUE THREAD

**Issue by AsitJena** [microsoft/vsts-extension-retrospectives#342]
Is there any access issue is there on this extension, OR by default the user who has the access rights on the project are able to see  the [retrospectives](https://github.com/microsoft/vsts-extension-retrospectives) tab under the project ( boards-->[retrospectives])

**Comment by mindlessroman** [comment]
@AsitJena could you explain this issue more? Do you have users who are not able to access boards? Or something else?
