### ISSUE TITLE
Board templates

### ISSUE THREAD

**Issue by polatengin** [microsoft/vsts-extension-retrospectives#35]
Can we define a custom template for retrospectives (with number of columns, column headers and anonymous status etc.) so it becomes easier to create a new retrospective board for each sprint?

_Original suggestion is made by Mohit Kumar and Geert Lommers on https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&ssr=false#qna_

**Comment by yayitserica** [comment]
Punting to perhaps 1.6 release.

**Comment by polatengin** [comment]
resolved by PR #75
