### ISSUE TITLE
"Contact Us" link should link to Q&A page, currently it links to "Overview"

### ISSUE THREAD

**Issue by yayitserica** [microsoft/vsts-extension-retrospectives#37]
Current status: links to https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives#qna

Desired status: links to https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&ssr=false#qna

![image](https://user-images.githubusercontent.com/15487798/86787132-c38e4480-c032-11ea-8b09-e6181e120d13.png)

**Comment by polatengin** [comment]
good catch, thanks for reporting this. since it's a very trivial issue, I'll resolve it real quick.

**Comment by polatengin** [comment]
it's done by one of the PRs I merged couple of weeks ago. closing the issue for now. please feel free to add a comment to re-open.
