### ISSUE TITLE
Task's in Retrospective boards is out of colums (see picture)

### ISSUE THREAD

**Issue by SimonSkroder** [microsoft/vsts-extension-retrospectives#372]
![image](https://user-images.githubusercontent.com/108676760/177162023-6b428847-bd5a-446d-8445-ab2f6ae92583.png)

**Comment by polatengin** [comment]
this issue should be fixed with v1.80.3

may I kindly ask you to double check, please, @SimonSkroder?

**Comment by SimonSkroder** [comment]
It is fixed - thank you! :)
