### ISSUE TITLE
Retrospectives Link failed to load

### ISSUE THREAD

**Issue by OttoKriedeman** [microsoft/vsts-extension-retrospectives#376]
After the latest update, we are receiving this error message and I am not sure if this is the same issue that others are seeing. Currently we are running TFS 2018. 
This started with the update to 1.80.1

![Retrospectives failed to load](https://user-images.githubusercontent.com/75992015/177561289-16cb67b1-41d0-4d55-a937-1a6bbc87e764.PNG)

**Comment by BennyBrowns** [comment]
Hi @OttoKriedeman this is also discussed in issue #371

**Comment by dstoddar** [comment]
Duplicate to #380
