### ISSUE TITLE
Bug: csv export tool not working properly

### ISSUE THREAD

**Issue by areathinkable** [microsoft/vsts-extension-retrospectives#382]
The csv export tool does not encode the commas, which is splitting the description into multiple columns

**Comment by dstoddar** [comment]
@areathinkable, thank you for raising awareness of the issue.

**Comment by mindlessroman** [comment]
I believe this was included in the latest release. @areathinkable - can you confirm?

**Comment by dstoddar** [comment]
@areathinkable , it's been resolved.
