### ISSUE TITLE
Reporting on retrospectives - query / dashboard

### ISSUE THREAD

**Issue by JBMHR** [microsoft/vsts-extension-retrospectives#384]
Our teams use the Retrospectives extensions in ADO, but I can only see them by opening one team & one sprint at a time, and although the history view does show multiple sprints it doesn't show the detail I want and doesn't seem to be configurable.  Is there a way of reporting across a number of teams/sprints, by query perhaps?  Ideally I'd like to build a dashboard to show, by team and by sprint, how many comments were made by feedback type (mad, glad, sad etc), and how many resultant work items were created.  I understand that this won't show the key detail of each comment, but at least I'd see the level of activity and whether or not retrospectives are actually being conducted.

**Comment by dstoddar** [comment]
@JBMHR , unfortunately, this capability does not exist and isn't on our roadmap. There are alternate ways to access the historical data, but most are clunky and require pulling the JSON and parsing.

**Comment by JBMHR** [comment]
OK, thanks for letting me know
