### ISSUE TITLE
Error when clicking History for some retros

### ISSUE THREAD

**Issue by gityup4567874** [microsoft/vsts-extension-retrospectives#386]
Error:  "We detected an error in the application"

**Comment by mnelsonwhite** [comment]
![image](https://user-images.githubusercontent.com/7707471/178634454-0c8fe35c-6276-44a9-b1da-e46dc3d86f5f.png)
Clicking on this causes the error `TypeError: can't access property "displayName", t.fields['System.AssignedTo'] is undefined`

**Comment by gityup4567874** [comment]
![retrospectives error](https://user-images.githubusercontent.com/109106761/179285569-17b5ef4f-b63f-497b-895e-f8d3d42e4141.PNG)

**Comment by gityup4567874** [comment]
Getting that error when clicking the arrow in History

**Comment by mindlessroman** [comment]
Hey folks - I have a hunch of what's happening here, but would like to confirm. Do you know if these items were assigned to team members who are no longer part of your organization?

**Comment by gityup4567874** [comment]
All assigned users are part of the organization.

**Comment by mindlessroman** [comment]
There was a release for 1.80.11 this past week, and I believe a fix for this was included. Are you still seeing this problem?

**Comment by gityup4567874** [comment]
The retro board history still has the "We detected an error in the application" for the existing boards that were created.

**Comment by polatengin** [comment]
I created a branch, a commit to the branch and I deployed the fix to dev environment. @mindlessroman , when you can repro the issue, can we check the solution on the dev environment, please?
