### ISSUE TITLE
vote count contrast issue

### ISSUE THREAD

**Issue by polatengin** [microsoft/vsts-extension-retrospectives#39]
I noticed the vote count on the retro board is very faded and hard to see. This is especially the case when it’s being shared in a meeting. For example, I couldn’t tell if the number is 6 or 8 during the meeting when someone else’s sharing their screen.

![contrast issue](https://user-images.githubusercontent.com/118744/86942324-abf7ae80-c14d-11ea-94e1-d5477fc2cfb6.png)

Would you consider using a different color with higher contrast for better accessibility?

_Original issue reported by Mandy Chan from Microsoft_

**Comment by JankaKoen** [comment]
Hi Engin! There are clear rules for accessibility and color contrast. I will make a suggestion to address and improve this. J.
