### ISSUE TITLE
Focus mode no longer works

### ISSUE THREAD

**Issue by ksoekarjo-shell** [microsoft/vsts-extension-retrospectives#390]
Focus Mode within Act no longer works, clicking it results in a white screen with the text "We detected an error in the application". 
![image](https://user-images.githubusercontent.com/93986767/178705865-ffac008e-c31c-47fa-b9cb-b711d62616a3.png)

**Comment by mindlessroman** [comment]
Hey @ksoekarjo-shell - Have you seen this with any recent releases? If so, can you provide more details, such as any console warnings?

**Comment by ksoekarjo-shell** [comment]
Hi @mindlessroman  - Thanks for checking in, this error stopped occurring about a week after we encountered it so issue can be closed.
