### ISSUE TITLE
Bug: Typing anything in the Group Feedback input box causes an exception

### ISSUE THREAD

**Issue by PhilipMurray** [microsoft/vsts-extension-retrospectives#392]
When trying to input anything into the group feedback input box I get "We detected an error in the application" error message
This happens on a a retro board with feedback items in the columns. I go to group some feedback by clicking on the feedback option and selecting Group feedback, when the new dialog pops up I try to input some text and the exception is thrown.

This is the error message:
![image](https://user-images.githubusercontent.com/5538058/179238974-5c629899-2879-43e3-8bbf-65aeb1d15bfa.png)

This is the input box field:
![image](https://user-images.githubusercontent.com/5538058/179238835-6dc6b6eb-4f9a-42fa-9c7c-d7f110bc10f6.png)

**Comment by lwong072022** [comment]
I get the same error when trying to group cards using the ellipsis menu. The other way to group cards using the drag + drop has also stopped working since upgrading to the 1.80.10 version. Both grouping options are now not working. Will the next update resolve this issue?

**Comment by BenDrage** [comment]
Any sign of this being fixed? It is damaging Retrospectives

**Comment by mindlessroman** [comment]
Fix is merged into main!

**Comment by mindlessroman** [comment]
Hey folks - I believe this was fixed in the latest release (1.80.13). @PhilipMurray , @lwong072022, can you confirm?

**Comment by mindlessroman** [comment]
Will close this now, but if something comes up we can investigate in a new issue.
