### ISSUE TITLE
Retrospectives not loading on DevOps server

### ISSUE THREAD

**Issue by cdvolvo** [microsoft/vsts-extension-retrospectives#397]
![Screenshot 2022-07-19 075817](https://user-images.githubusercontent.com/109596326/179744912-cfedc036-ec01-4554-a30d-d60f99d9dcae.png)
After the last update to Retrospectives, I cannot load it or retrieve previous retrospective data. This is a show stopper for my team. We need it corrected ASAP please.

**Comment by reavild1** [comment]
Our enterprise has the same issue. Is it because our DevOps is hosted on premise using http: protocol?

**Comment by flashp0wa** [comment]
We are facing the same issue... I couldn't find any previous versions to use it until this one gets fixed

**Comment by polatengin** [comment]
closed to track the issue on #380
