### ISSUE TITLE
Multi-column display in one bucket

### ISSUE THREAD

**Issue by renebefort** [microsoft/vsts-extension-retrospectives#398]
Hello!

With the latest update, the cards in a bucket are only in one column. In an older version you could change the zoom and then the maps were displayed in multiple columns. This was very helpful, special for the grouping.

Regards René

**Comment by annbern** [comment]
Agreed. This feature existed until around July 1, 2022. Now it's gone. Retrospectives seem to be a deprecated extension.

**Comment by polatengin** [comment]
🥳 new version just released (v1.80.11) with the fix

please update the extension on your environment 👍

**Comment by polatengin** [comment]
> Agreed. This feature existed until around July 1, 2022. Now it's gone. Retrospectives seem to have been abandoned.

hi @annbern , I added a new UI toolkit to the extension, this issue was a side-effect.

sorry for the inconvenience.

extension is far-from being abandoned, contrary, it's actively under development, that's why sometimes I break functionalities and need some time to fix them 🤦‍♂️
