### ISSUE TITLE
Feature Request: Hide Cards during Collect stage

### ISSUE THREAD

**Issue by ArieHein** [microsoft/vsts-extension-retrospectives#4]
Finally you went OSS !!  <3

When collecting cards from various team members, it would be nice if "refreshing" the window will not happen so members can not see each others cards as it might influence their own input.

Continue "refreshing" the cards view, after the stage is over.

**Comment by thomasvdb** [comment]
I'm interested into this as well and I'm willing to invest some development time in this feature.
Looked into the code to get an estimate of how much work it would be and I'm seeing two possibilities to solve this:

1. Disable the broadcast events as long as you're in the "Collect" phase
1. Still allow the broadcast events to happen but hide the cards with CSS as long as you're in the "Collect" phase

Option 2 seems the best option as the data is already available on each client and switching is quite easy then.

**Comment by ArieHein** [comment]
The problem is that "When you are in the collect phase" is that you cant really decide programmatically "When you are in the collect phase", there are no roles so the creator is the one choosing when its time for phase changes, else you would be able to add to his view a checkbox / button declaring end of collect phase and start of next phase.

**Comment by thomasvdb** [comment]
That's correct and that's how we're using it right now. 
The scrum master decides when we're going to the next phase and as the scrum master is sharing the screen this would work for our setup.

However, a button indicating the end of the "Collect" phase would probably a better idea and more suitable for multiple scenarios/setups.

**Comment by mpth** [comment]
I would suggest to show card activity from other team members but conceal what they are writing. This would emulate closer what happens in a live retrospective.  🙂

**Comment by thomasvdb** [comment]
@mpth That would be an option as well. In that case we maybe need to add a placeholder text or image? Because otherwise it may seem that the board is broken if there are empty cards popping up :) 

Or do you have another UX design in mind?

**Comment by ArieHein** [comment]
You can animate the cards poping in the view with face down as people entering them. When time is up (either configurable or via a button), the cards flip to display the content.

**Comment by mpth** [comment]
Yeah something like that. Or use a CSS effect to blur the text.

**Comment by ArieHein** [comment]
Btw, you can still show the card face sowing up with the name of the person that is entering the data, just blur the lower part when there content is.

**Comment by thomasvdb** [comment]
Ok, great ideas and should require minimum changes to the PR.

@ArieHein Could you eloborate more on the comment you gave in the PR? You talked about not linking the pressing of the other tabs?

**Comment by ArieHein** [comment]
I have, in the PR.

**Comment by lindhe** [comment]
This is broken in mobile view on desktop. I guess the blur does not scale correctly with zoom level.
