### ISSUE TITLE
Version 1.80.10 - Live syncing not working on hosted ADO

### ISSUE THREAD

**Issue by thubble** [microsoft/vsts-extension-retrospectives#401]
We use hosted ADO, and yesterday (July 21) we noticed an error message `We are unable to connect to the live syncing service. You can continue to create and edit items as usual, but changes will not be updated in real-time to or from other users.` As the message says, live syncing was not working and we all had to keep refreshing the page. The issue is still present today. The issue happened on several different machines with different browsers, connecting from different locations.

We only have retros every 2 weeks so we can't pinpoint exactly when it started, but the last one was on July 7 and everything was working fine then. According to the extension update history, it was on version 1.80.4 at that time (since July 6), and then on July 20 a bunch of updates happened to bring it to 1.80.10.

The current hosted ADO version appears to be `Version Dev19.M206.1 (AzureDevOps_M206_20220714.5)` - I'm not sure if that could have anything to do with it.

I did notice the following output in the DevTools console:
```
ReflectBackendService: not hosted on Azure DevOps		reflect-bundle.js:2
isHostedAzureDevOps: hostAuthority=dev.azure.com		reflect-bundle.js:2
ReflectBackendService: isHosted=true				reflect-bundle.js:2
isHostedAzureDevOps: hostAuthority=dev.azure.com		reflect-bundle.js:2
```

**Comment by thubble** [comment]
It looks somewhat similar to https://github.com/microsoft/vsts-extension-retrospectives/issues/374 - but I don't see any SignalR errors in the DevTools console.

**Comment by sbingham-MET** [comment]
our ADO is cloud hosted, we assumed this issue was related to the ADO service degradation morning but it has still not been resolved.

**Comment by thubble** [comment]
The issue appears to be fixed.
