### ISSUE TITLE
[DOCS] Update Readme page to reflect 1.5 changes

### ISSUE THREAD

**Issue by yayitserica** [microsoft/vsts-extension-retrospectives#43]
Update Readme page to reflect 1.5 changes.

Updated pages should be these two:

- https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&ssr=false#overview
- https://github.com/microsoft/vsts-extension-retrospectives/blob/master/README.md

**Comment by polatengin** [comment]
I think I fixed this issue long time ago, please feel free to reopen it if you think the docs still missing some information
