### ISSUE TITLE
Creating retrospective group always crashes

### ISSUE THREAD

**Issue by alancshi** [microsoft/vsts-extension-retrospectives#430]
In my retrospective board, I went to the "groups" tab, clicked on an item, and tried to create a group. The second I type any character to give the group a name, I get a page that says an error occurred.

**Comment by alancshi** [comment]
"We detected an error in the application" is the message

**Comment by AntonZakharoshka** [comment]
I have the same issue.

**Comment by mindlessroman** [comment]
Hey folks - I believe this was fixed with the most recent release (1.80.13) that release yesterday evening. Have you seen it today?

**Comment by AntonZakharoshka** [comment]
> Hey folks - I believe this was fixed with the most recent release (1.80.13) that release yesterday evening. Have you seen it today?

Thanks a lot. It works great

**Comment by mindlessroman** [comment]
Hurrah! So glad to hear. I'll close this for now.
