### ISSUE TITLE
Add a link from VS Marketplace to this repo

### ISSUE THREAD

**Issue by oigres200** [microsoft/vsts-extension-retrospectives#46]
The listing of this extension is missing the Project Details section on Visual Studio Marketplace, making it difficult to discover that the extension is open source and being developed here.

**Comment by yayitserica** [comment]
@polatengin do you think we can add this to v1.5?

**Comment by polatengin** [comment]
thanks for reporting this @oigres200 , I'll update the Project Details section to make it more visible that it's open sourced here.

/cc: @yayitserica

**Comment by polatengin** [comment]
it's done, link to this repo is added to marketplace details
