### ISSUE TITLE
Not able to load the Retrospectives board

### ISSUE THREAD

**Issue by AsitJena** [microsoft/vsts-extension-retrospectives#482]
Hello Team,

I am Asit Jena, managing our Devops organization. I have installed the extension **"Retrospectives"** on our Org. on 8th Feb 2020. It has been using by all the projects.

The issue one of the users is that, while click the Retrospective tab under Boards- the Board is loading with an empty (blank space) nothing is showing on, but for all other user with that group, they have its loading perfectly. The user was trying load it from different browser (tested with Opera Version 92.0.4561.33, Firefox Version101.0.1, edge Version 106.0.1370.47 and Chrome) but no luck.

So, question is that how this is possible? the user already has the Basic license, and he is part of the project contributor group. While other has the same license and under the same project group and they are able to see the board.

Could you please help me here how user can overcome this issue. ? attached with the screen shot (one for which retrospective board is loading and other don't load the same)

Please suggest / advice ?

![Error-Retrospective- Error for a user](https://user-images.githubusercontent.com/42863668/203999980-60018a4e-0498-48cd-a21d-941859264856.PNG)
![Retrospective-all users-load the Borad](https://user-images.githubusercontent.com/42863668/203999992-9504b795-9700-42cc-bef7-21c8bffed73f.PNG)

**Comment by mindlessroman** [comment]
Hi @AsitJena - Could the affected user try clearing their board history? This is under the hamburger icon in the upper right of the tool.
<img width="230" alt="image" src="https://user-images.githubusercontent.com/7254163/206288123-98aa1980-bffd-4c55-9466-acf8e711373d.png">

That has helped folks in the past. Let us know if this is still being troublesome after trying that.

**Comment by AsitJena** [comment]
@mindlessroman : Thank you and  will have a check with the user for the same and update you accordingly.

-Asit

**Comment by TheMonzel** [comment]
Hi @mindlessroman 
Our team has the same issue. Clearing the visit history helped as far as I know.

**Comment by AsitJena** [comment]
@mindlessroman : Thank you and its working as expected.

**Comment by mindlessroman** [comment]
Awesome! I'm so glad!
