### ISSUE TITLE
Feature Change: In focus mode, Show Original column name for any grouped items

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/vsts-extension-retrospectives#489]
**Is your feature request related to a problem? Please describe.**
Noticed that this feature was missing in the focus mode. It's shown in all the other views of the board

**Describe the solution you'd like**
Like the title says - show any grouped items' original columns while in the focus mode.

**Describe alternatives you've considered**
n/a

**Additional context**
Should be a quick fix.

**Comment by JStuve** [comment]
Resolved with #544
