### ISSUE TITLE
Azure DevOps Boards - Retrospectives data export?

### ISSUE THREAD

**Issue by kscottagnew** [microsoft/vsts-extension-retrospectives#492]
I can see it is easy to export Retrospective data to a .csv file but is there a way to also have access to export the data from the TEAM ASSESSMENT survey similar to how you can export the Retrospective data?

**Comment by polatengin** [comment]
I released a new version, like a month ago, with export and import data features.

can I kindly ask you to check this feature, please?

closing this issue for now, please feel free to re-open if you want further support.
