### ISSUE TITLE
Extension Permissions

### ISSUE THREAD

**Issue by tthb1** [microsoft/vsts-extension-retrospectives#498]
**Is your feature request related to a problem? Please describe.**
When the extension is installed, it is impossible for me to define clear permissions on the retrospectives.
Indeed, as soon as a reader is authorized on the project, he can access all the retrospectives in reading and writing.

**Describe the solution you'd like**
Allow in the Security tab of the project or collection to define who can access retrospectives and who can write (or limit access to the project team at less)

**Describe alternatives you've considered**

**Additional context**
In Scrum, retrospectives are for the product team. In this case, when the backlog is shared with an entire organization or when it is public, it reduces the ability of team members to express themselves.

**Comment by Wandernoth** [comment]
100% agree on this issue!
Retrospectives should be a safe place and especially with the history being available it should only be accessible by the DevOps team.

**Comment by Luuk-Kramer** [comment]
I'd like to support this too.
We want to use the retrospective extention at my work but that is impossible without this feature. We have several teams and we would currently be able to see eachothers retrospective boards. And as Johndoe1982 above me said, Retrospectives should be a safe place.

**Comment by tthb1** [comment]
Hello,

I'm coming back to you regarding this change request. Is it possible to integrate rights management in the extension?

THANKS

**Comment by omegasupreme3** [comment]
The **core principle** of the **retrospective** is that it should be **a safe space**. How is it possible that this feature request after 3 years still does not support this? Making sure that only members of the Scrum/Agile team can access the board should have been the first thing to implement ... Instead of nice graphs, new icons to select. Please give this feature request real priority!

These issues are addressing the same problem:

- #49 
- #5

**Comment by dphanson63** [comment]
I can see a Permissions tab, but I find the tab is not working.  The same names repeat indefinitely, sometimes checked and sometimes unchecked, and I cannot update the permissions, even if I create the board or have project manager role.
