### ISSUE TITLE
Retrospectives not loading on DevOps server - Bug

### ISSUE THREAD

**Issue by cdvolvo** [microsoft/vsts-extension-retrospectives#499]
This is the same issue that we had earlier in 2022. The retrospectives app will not load onto the server. We cannot access the extension
s the same issue that we had earlier in 2022. The retrospectives app will not load.
![retrospectives](https://user-images.githubusercontent.com/109596326/215771866-41301869-fca2-4e10-9547-a904e7043c35.png)

**Comment by cdvolvo** [comment]
https://github.com/microsoft/vsts-extension-retrospectives/issues/397#issue-1309414814

**Comment by martingbrown** [comment]
Have you tried using https? One of my clients had this, it appears to be doing some kind of matching on the URL. Also we had multiple domains for the same site and only one of them worked.

**Comment by ka-kalee** [comment]
I recently upgraded ADO from 2019 to 2022. I have the same issue where Retrospectives stuck on the loading page. I am using https.

**Comment by cdvolvo** [comment]
We are connecting directly to our TFS server. There is no http or https at the beginning of the URL, just the  servername.
