### ISSUE TITLE
Templates for retro boards

### ISSUE THREAD

**Issue by iste2** [microsoft/vsts-extension-retrospectives#504]
**Is your feature request related to a problem? Please describe.**
I have to create a completely new board for every retro meeting

**Describe the solution you'd like**
I would like to create a new board based on a template.

**Describe alternatives you've considered**
Copy a board

**Comment by hoborp-kulcs-soft** [comment]
+1

**Comment by RoyalWulf** [comment]
+1

**Comment by JStuve** [comment]
Resolved with #561
