### ISSUE TITLE
Retrospective reporting "We detected an error in the application"

### ISSUE THREAD

**Issue by bryonmyers99** [microsoft/vsts-extension-retrospectives#511]
**Describe the bug**
When accessing a retrospective in a certain ADO project the screen is showing "We detected an error in the application."  We are able to access retrospectives of teams in other projects in the same organization without any issues.

** Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[X ] No

**To Reproduce**
1. Go to Boards.
2. Click on Retrospectives
3. The retrospective quickly flashes on the screen but then disappears.
4. Receive an error "We detected an error in the application."

**Expected behavior**
Usually the retrospective will load.

**Screenshots**
See attached screenshots w/ organization/project id's omitted.  Can provide more details as needed.

**What screen type are you seeing this on ?**
[X] Desktop
[ ] Mobile

**Additional context**
This was working for the end users earlier in the day but is no longer working.
![error1](https://user-images.githubusercontent.com/61289773/221962548-e3290b0b-68d8-4033-9566-00201d2e35b2.png)
![error2](https://user-images.githubusercontent.com/61289773/221962567-fc937846-11fd-4f7f-b691-372d5c93bcf3.png)

**Comment by polatengin** [comment]
hi, I think I solved this issue. please re-try 👍

**Comment by plynch99** [comment]
I am still seeing this issue
