### ISSUE TITLE
Ability to create Retrospectives Templates or Duplicate Existing ones

### ISSUE THREAD

**Issue by tbraun1551** [microsoft/vsts-extension-retrospectives#516]
**Is your feature request related to a problem? Please describe. **
My team uses a new retro board for every retro. For our retro boards, we have a four columns. 
1. Goals from last retro
2. What went well
3. What didn't go well
4. Future improvements

Ideally, we would be able to create new boards from a template or at least duplicate and reuse older boards. This way, the new columns to not need to be made by hand every time.

**Comment by FH-Inway** [comment]
Would love such functionality. This is similar to #504

**Comment by JStuve** [comment]
Resolved with #561
