### ISSUE TITLE
Ability to report on retrospective items using Analytics Views

### ISSUE THREAD

**Issue by rwhitworth127** [microsoft/vsts-extension-retrospectives#52]
It would be helpful to be able to report on our retrospective items like we do other work item types. Is there any possibility of retrieving these items through API? Or creating the items as custom work item types so they can be reported on?

**Comment by ArieHein** [comment]
Towards the end of the retrospective, after all the team has voted, you are spouse to create new features or user stories / PBIs, so those workitems already exists. If you want to note that those came as a result of a retrospective, add a tag and add a URL link to the retrospective URL. Makes it much easier then messing with API

Creating specific workitems for this is a bit counter intuitive  as its duplication of data and involves changing  process template, which is possible in an inherited one but impossible if a project uses the defaults ones. 

What i think would be a nice thing to have is a widget that comes with extension and placing that on a dashboard.

**Comment by polatengin** [comment]
as @ArieHein suggested, it can be done via creating work items for every "important" feedback, and query those work items via regular Azure DevOps API.

since this issue has a low interaction, I'm closing it for now. please feel free to add comment and re-open it.
