### ISSUE TITLE
Is it possible to restore a retrospective board?

### ISSUE THREAD

**Issue by hansenbc** [microsoft/vsts-extension-retrospectives#538]
Our team had a retrospective board in ADO accidentally get deleted. Is it possible to restore a retrospective board that has been deleted?

**Comment by gesexton** [comment]
Any update to this question?  Thanks

**Comment by JStuve** [comment]
@hansenbc @gesexton 

Looks like there is a good thread about this request #32. If you find it helpful and able to recover data via the API, please submit a feature request and we can look into better recovery solutions within the extension.
