### ISSUE TITLE
Is there a REST API for create a new retrospective?

### ISSUE THREAD

**Issue by xmdanni** [microsoft/vsts-extension-retrospectives#569]
Hi, I want to automate some manual work (like create a new retrospective) in the scrum process in my team. Wondering if there is a REST API I can call before every sprint to create a new retrospective with below settings? The title is the only variable for me and I can generate the title in my code before calling this API. I want it to return the link of the board it just created (like `https://dev.azure.com/abc/Def/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=123&boardId=4567`) to me. It will be even better if there is a connection in [Microsoft Power Automate](https://learn.microsoft.com/en-us/connectors/visualstudioteamservices/#actions) so that I can directly use the action in my workflow.
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/34960224/995e0048-02a8-4f61-af4b-04b11c89dd59)

**Comment by cgrippon** [comment]
Hello, any update on this request ? I search to connect PowerBi on one API.How can I do it ?
