### ISSUE TITLE
Unable to load Retrospectives when an enterprise has CSP in place with added proxy specific sub-domains

### ISSUE THREAD

**Issue by ovishesh** [microsoft/vsts-extension-retrospectives#57]
We are constantly hitting an issue with an enterprise that has CSP policies in place via a proxy which messes with domain names and can trigger Content Security Policy issues. We end up using this extension as a work around - https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden. It will be great to have support for this scenario out of the box, as the other aspects of the ADO environment works just fine behind this proxy.

**Comment by polatengin** [comment]
I think I fixed this issue long time ago, please feel free to reopen it if you see load is still blocked
