### ISSUE TITLE
WI with state "Removed" should not count towards Work Items pending

### ISSUE THREAD

**Issue by Ellyster** [microsoft/vsts-extension-retrospectives#59]
If the state of a WI created for a Feedback item is changed to "Removed", this item still appears as pending in the history tab.

For example:
![imagen](https://user-images.githubusercontent.com/4518921/94128835-e7f00500-fe5a-11ea-9933-2d549451d9cd.png)

![imagen](https://user-images.githubusercontent.com/4518921/94128525-8f206c80-fe5a-11ea-9770-e0b726d52ddc.png)

![imagen](https://user-images.githubusercontent.com/4518921/94128361-5e403780-fe5a-11ea-8e04-d70099f80f66.png)

**Comment by polatengin** [comment]
resolved by PR #68
