### ISSUE TITLE
Retrospective is taking time to load. This is happening in our organization for while in multiple regions. Also, consider this extension to be part of scrum template by default. 

### ISSUE THREAD

**Issue by MeenaElangovan** [microsoft/vsts-extension-retrospectives#60]
As Retrospectives are essential to Agile teams I would suggest in taking up the code of it and put it in the core of ADO.

_Originally posted by @HappyFlow in https://github.com/microsoft/vsts-extension-retrospectives/issues/38#issuecomment-666170763_

**Comment by mpth** [comment]
Hey Meena,

Are you using Azure DevOps Server (on prem) or Azure DevOps Services (Cloud)?

**Comment by MeenaElangovan** [comment]
Hi Michael,

Thank you for looking into this issue!

We are using Azure DevOps Services (Cloud).

Regards,
Meena

**Comment by polatengin** [comment]
I think I fixed this issue long time ago, please feel free to reopen it if you think it still takes long time to load
