### ISSUE TITLE
Copy retrospective link is not working

### ISSUE THREAD

**Issue by richardzaat** [microsoft/vsts-extension-retrospectives#61]
when using "Copy retrospective link" we get a link to the project/team, but no longer to the actual retrospective. Please fix, as the feature has been very useful for us

See nr of comments on the marketplace as well: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.team-retrospectives&ssr=false#qna

**Comment by thomasvdb** [comment]
@richardzaat This is a duplicate issue as it's already logged here: https://github.com/microsoft/vsts-extension-retrospectives/issues/50
