### ISSUE TITLE
CONTRIBUTING.md is incorrect

### ISSUE THREAD

**Issue by ericstj** [microsoft/vsts-extension-retrospectives#62]
This file mentions that a `Retrospectives.sln` file should exist, but it does not.

`npm install` does not work from the root, as implied, but it does work.  It does work from the RetrospectivesExtension.Frontend folder.

`npm run build` does not work from this folder, instead you need to use `npm build:d` which appears to build the dev version of the package.  Same goes for pack, it should be `pack:d`

This is as far as I got.  Found some other broken links in the doc like https://github.com/microsoft/vsts-extension-retrospectives/tree/master/Backend.

I may be able to fix some of these, but had to pause this project before finding a working e2e workflow.

**Comment by polatengin** [comment]
hey Eric, may I kindly ask you to check if #65 is solving this issue, please?

**Comment by polatengin** [comment]
#65 solved the issue, thanks for reporting it, @ericstj
