### ISSUE TITLE
Support Timeline activity

### ISSUE THREAD

**Issue by James-Nance** [microsoft/vsts-extension-retrospectives#63]
Allow users to place their issue on a page and move them around freely.  This would support a timeline activity where events / items need to be constantly sorted and placed in relation to one another.

**Comment by polatengin** [comment]
may I ask you kindly to elaborate this request a bit, please?

**Comment by polatengin** [comment]
it's been almost a month and no update on this issue, closing it for now.

please feel free to add comment and re-open it.
