### ISSUE TITLE
Azure Retrospectives not Loading (Blank page with loading screen) 

### ISSUE THREAD

**Issue by lester-manglicmot** [microsoft/vsts-extension-retrospectives#671]
Hi Team,

The Retrospectives extension is not loading in our Azure Devops Organizations.

Any idea what may be the issue or how to fix? 

Thanks in advance.

Lester

**Comment by ecanop** [comment]
I have exactly the same problem. Since yesterday the retrospective page is not loading.

![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/63523513/5464cdfa-09ad-44e6-9c22-ecd03edb0967)

**Comment by mjmurtag** [comment]
+1 still facing this issue.

**Comment by polatengin** [comment]
I found the problem (thank you @mjmurtag) there is an infinite loop, I'll fix it right-away and release a new version with the fix 👍

**Comment by polatengin** [comment]
I think I solved the issue, testing on a test environment now.. thanks for being patient!..

**Comment by polatengin** [comment]
it seems the issue is fixed with PR (#677)

closing this issue for now, if you see the issue continues, please feel free to re-open it 👍
