### ISSUE TITLE
Retrospectives Link not Loading

### ISSUE THREAD

**Issue by OttoKriedeman** [microsoft/vsts-extension-retrospectives#712]
A team member has created a Retrospective and when the link is shared, and we try and open the link, it spins and never opens. This is for every user that attempts to open the link. We can select Retrospectives from the side panel and go through the process of creation but that is it. 

We are using the latest version 1.92.12 and are running Azure DevOps 2022 on premises. We are using a combinations of Desktops and virtual desktops in Citrix. 

Attached is a screenshot of what I am seeing using Developer Tools In Chrome. 
![Retrospectives failed to load](https://github.com/microsoft/vsts-extension-retrospectives/assets/75992015/bf9f9510-730e-493e-a323-f60f66aaf91a)

**Comment by polatengin** [comment]
I think I fixed this issue in one of the PRs that I merged, so, I'm closing this for now.

Please feel free to re-open if you think there is more to do 👍
