### ISSUE TITLE
Hi Team, We are facing loading issue in Retrospective sessions. It took almost 1-2 mins to load the page for most of the users. Please find attached screenshot

### ISSUE THREAD

**Issue by Hitaishi2** [microsoft/vsts-extension-retrospectives#731]
**Describe the bug**

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[ ] No

If Yes, what version of the extension?

**To Reproduce**

**Expected behavior**

**Screenshots**
![MicrosoftTeams-image](https://github.com/microsoft/vsts-extension-retrospectives/assets/165376925/83178881-8594-447f-bfe5-dc7574fb0348)

If applicable, add screenshots to help explain your problem. If you have any developer console information
that feels relevant, that is also helpful!

**What screen type are you seeing this on ?**
[ ] Desktop
[ ] Mobile

**Additional context**

**Comment by polatengin** [comment]
can I kindly ask you to open Network panel in the Developer Panel (F12) and see the longest requests, please?
