### ISSUE TITLE
Retrieve Retrospectives of a Deleted Team

### ISSUE THREAD

**Issue by CodyPacker** [microsoft/vsts-extension-retrospectives#738]
We have deleted a team in ADO as we have moved them across projects, is there any way to pull their archived retrospectives? I don't see any recovery method recommendations, if there are any.
Do retrospectives get permanently deleted once the team is deleted?

**Comment by polatengin** [comment]
Retrospective Extension stores data in the central place that Azure DevOps itself gives to the extensions. So, Azure DevOps data structures and extension data structures are not tightly coupled.

That means, even after you deleted a team in Azure DevOps, it's still exists on Retrospective Extension data storage.

Unfortunately there is no easy way to access that data.

You can export _all_ data from Retrospective Extension, or you can use Api calls to query data. If I remember correctly here is an example; https://github.com/microsoft/vsts-extension-retrospectives/issues/32
