### ISSUE TITLE
Retro board did not save added feedback

### ISSUE THREAD

**Issue by AlexHoffman-T10** [microsoft/vsts-extension-retrospectives#745]
**Describe the bug**
I went to add feedback to the retro board. Upon hitting enter, the feedback box turned blank and all text inside was deleted. I added several and they all appeared blank. When I refreshed the page, my added feedback disappeared. It was about 20 minutes later a different teammate tried and was successfully able to add their feedback. 

**Are you using the Retrospectives Tool on-prem?**
[x ] Yes
[ ] No
I'm guess this means on premises? 

If Yes, what version of the extension?
1.92.12 (Latest)

**To Reproduce**
Have someone create retro board
Click board in after it is pasted into teams
Attempt to add feedback
Note that feedback boxes are empty instead of full of text entered.

**Expected behavior**
Feedback entered should not be deleted.

**Screenshots**
![retro](https://github.com/microsoft/vsts-extension-retrospectives/assets/156841631/66f17929-9fe7-48b7-8405-79c7d3bfac88)

**What screen type are you seeing this on ?**
[x] Desktop

**Comment by polatengin** [comment]
I fixed a lot of things since this issue created. Closing the issue for now, please re-open it if you see the issue persists.
