### ISSUE TITLE
 Retrospective board is not loading/Visible on Azure devops board.

### ISSUE THREAD

**Issue by Avianshnl** [microsoft/vsts-extension-retrospectives#757]
**Describe the bug**
 Retrospective board is not loading/Visible on Azure devops board.

**Are you using the Retrospectives Tool on-prem?**
[ ] No

If Yes, what version of the extension?
1.92.12

**To Reproduce**

<img width="950" alt="Screenshot 2024-01-18 Azure" src="https://github.com/microsoft/vsts-extension-retrospectives/assets/171254307/8a327f4f-48a2-4e41-8ea8-840fb909d7cc">

**Expected behavior**
Board is not visible.

**Screenshots**
Screen shot added

**What screen type are you seeing this on ?**
[ ] Desktop

**Additional context**

**Comment by Avianshnl** [comment]
Can any one please pick this issue.

**Comment by maurice-hebben** [comment]
Please we see this issue also. As Project Admin in On Prem (2020) I do not have this issue, but other team members (with less permissions) cannot load...

**Comment by polatengin** [comment]
Hi, can you open Developer Panel (F12) and check the messages in the Console tab, please?

**Comment by write2amitv** [comment]
Hi @polatengin 

Please find the logs attached
[devops.OnPremRetroboard Issue-1722343053175.log](https://github.com/user-attachments/files/16428346/devops.OnPremRetroboard.Issue-1722343053175.log)

**Comment by ravening** [comment]
I was also facing the same issue. I clicked on the hamburger icon which is present to the left of "Whats new" and selected "Clear Visit History" and then did the hard refresh on chrome and that solved the issue.

Probably this will help others as well.

**Comment by PratMoha** [comment]
We're also facing same issue, no retro boards aren't available.
