### ISSUE TITLE
Unable to Add Feedback Items to Retrospective Board

### ISSUE THREAD

**Issue by AHughes1992** [microsoft/vsts-extension-retrospectives#774]
**Describe the bug**
When trying to add new items to a retrospective board, it fails to successfully add the item. This time last week, the board was allowing new items to be added.

**Are you using the Retrospectives Tool on-prem?**
[x] Yes
[ ] No

If Yes, what version of the extension?
1.92.13. This seems to have updated just earlier today.

**To Reproduce**

1. Open up a retrospective board
2. Click on 'Add new feedback' in any of the columns

**Expected behavior**
When new feedback is added, it is saved to and appears on the retro board it has been added to.

**Screenshots**
If applicable, add screenshots to help explain your problem. If you have any developer console information
that feels relevant, that is also helpful!
When adding feedback:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/e275342d-07b1-4a18-a91c-b9aed09e5b73)

After submitting feedback:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/3179c303-182d-4312-a3c5-e6561426b96d)

After refreshing page:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/7fcd0e83-a83d-4233-a8c0-cabb6486ab50)

Below is a console error we get on submitting and item:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/3e8f480e-3054-4415-9348-737b4a67a0ee)

**What screen type are you seeing this on ?**
[x] Desktop
[ ] Mobile

**Additional context**
As mentioned, this only seems to be happening since the update that was released earlier today. The last known time an item was added was at a retrospective this time last week (28/06/2024).

There is also another issue that has come up at the same time - we are unable to add/edit retrospective boards. If this needs raising as separate bug, please advise and I'll raise it. When trying to create/edit a retrospective board we get:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/88c72ae2-b325-468b-95ce-403e9957f407)

Which has a console error of:
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/51366309/1532d587-1af0-48d7-937a-f7fb76ff3752)

**Comment by polatengin** [comment]
I just updated randomizer logic, PR #776 should fix this. please let me know if the issue persists
