### ISSUE TITLE
Obscure Feedback Feature - Blurring Own Feedback + Can't Edit Once Entered

### ISSUE THREAD

**Issue by tyfeather** [microsoft/vsts-extension-retrospectives#777]
**Describe the bug**
When the 'obscure feedback' setting is enabled, users are unable to edit their feedback once submitted and their submitted feedback is also blurred as if it were another user's.

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x] No

If Yes, what version of the extension?

**To Reproduce**

1. Create new board with 'Obscure Feedback' setting enabled.
2. Create feedback card.
3. Note feedback is blurred and unable to edit once entered.

**Expected behavior**
Users should not see their own feedback blurred and they should be able to edit/adjust after submitted.

**Screenshots**
If applicable, add screenshots to help explain your problem. If you have any developer console information
that feels relevant, that is also helpful!

**What screen type are you seeing this on ?**
[x] Desktop
[ ] Mobile

**Additional context**

![Retro Bug 2](https://github.com/microsoft/vsts-extension-retrospectives/assets/148817528/a7022f71-a879-4128-b53a-b9fc5116fcdd)
![Retro Bug](https://github.com/microsoft/vsts-extension-retrospectives/assets/148817528/ff1b482e-005c-4caf-a46e-e904e2a2fb84)

**Comment by JanaVPetrova** [comment]
+1 I also experience the same issue.

**Comment by WilliamDAssafMSFT** [comment]
Experiencing the same issue. Hard to add new feedback to a blurred textbox.

![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/74387232/7c1d8a59-65c7-41b2-9521-894d5a24efcb)
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/74387232/0c3313c3-cce7-4ad4-8ce3-4bb104dec05a)

This appears on a retro that was created about a month ago in early June, with the 
![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/74387232/d6695b9d-5bd4-40a1-9efc-42d66b4b5556)
option, but not on new retros.

**Comment by agnieszkapuzio** [comment]
It's also happening on on-prem Azure DevOps

**Comment by jeremyperez-kimballmidwest** [comment]
+1 same issue.  Also, it appears to be linked to the "Do not display names in feedback" option.

**Comment by rjhennessey** [comment]
My team is seeing this behaviour as well. This week is the first time we noticed it, since our last Retros were two weeks ago. It was fine two weeks ago, as far as I know..

**Comment by taspeotis** [comment]
I suspect it's related to

https://github.com/microsoft/vsts-extension-retrospectives/pull/772

```
    const hideFeedbackItems = this.props.hideFeedbackItems && (this.props.userIdRef !== getUserIdentity().id);
```
