### ISSUE TITLE
Feedback is obscured in all phases, not just Collect phase

### ISSUE THREAD

**Issue by jeremyschultz** [microsoft/vsts-extension-retrospectives#779]
**Describe the bug**
Starting between 6/25/24 and 7/9/24, retros with the "Obscure feedback of others until after Collect phase" setting will obscure everyone's feedback including the user. CSS blur is active when you create a card and you can't read what you are writing until you exit the Collect tab.

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[ ] No

If Yes, what version of the extension?

**To Reproduce**

1. Create a retro with the Obscure Feedback setting turned on.
2. Create a new card.

**Expected behavior**
The card is visible and text is clear during entry.

**Actual behavior**
The card is blurred. Text can be entered but it's also blurred.

**What screen type are you seeing this on ?**
[ X ] Desktop
[ ] Mobile

**Comment by microbotas** [comment]
I have the same issue...

![blurRetrospective](https://github.com/user-attachments/assets/e9cb7794-c3eb-42b7-a2d0-133ddddf2b99)

**Comment by DaveP-NZ** [comment]
Same issue. Started with the latest release and affects all newly recreated retrospectives and all historical ones.

**Comment by Exormeter** [comment]
I have also the same issue, first time that we noticed it was a week ago on July 09.

**Comment by andrewcurriestarr** [comment]
Also have the same issue.

**Comment by rjhennessey** [comment]
My team is seeing this behaviour as well. This week is the first time we noticed it, since our last Retros were two weeks ago. It was fine two weeks ago, as far as I know..

**Comment by elduddz** [comment]
me three!
