### ISSUE TITLE
Feature Request: Configure Maximum votes for retrospective

### ISSUE THREAD

**Issue by gernd** [microsoft/vsts-extension-retrospectives#8]
It would be helpful to have a configuration for setting the maximum available votes for a retrospective. 

Usecase:
For recent retrospectives that I had with the team it was helpful to limit the number of votes per attendee in order to identify the most important topics (and especially prevent people from upvoting "their" topic multiple times which is currently possible)

**Comment by mpth** [comment]
Definitely needed. The moderator should be able to set the maximum at the start or the retro or maybe even change it during the retro.

I find that often the group decides ad-hoc together  on the max value after the collection phase so it would be bad if the value was not changeable by then.

**Comment by thomasvdb** [comment]
I was just wondering, what if there were already votes given and the max value is configured/changed during the retrospective which is lower than what a person has used in terms of votes?

Is it an option to disable changing this value once someone started voting?

**Comment by gernd** [comment]
@ArieHein I see your points and I think they are valid.

I agree that a visual indication on the board how many votes each user has given should be sufficient and would improve the current situation (and does not need an additional moderator role, rights management and so on)

**Comment by djbyrd** [comment]
The number of votes can be set when the retrospective is created, like setting it to anonymous. If the number of votes is not enforced, a way to un-vote for accidental overvoting should be provided.

**Comment by ArieHein** [comment]
add to my original idea a tag showing the overall votes used so far on all ideas to complement general visibility as we know how many people are attending the retro and the number of "agreed votes" so the math would be simple. Again the main objective is not to hardcode limits but increase trust

**Comment by attilabertok** [comment]
My two cents is this could be useful - trust issues aside, vote value inflation could be avoided by limiting the number of votes (avoiding the situation where I'm casting a vote here, two there, another two there, and one here as well, as these are **all** important issues, meanwhile another team member casts only two total votes, therefore my opinion would dominate the retro results).
I'd love to see this introduced in about three steps:
1. make it possible (but not obligatory) to limit the vote count
2. make it possible for a user to remove a vote they cast (and return that vote to the user's vote pool)
3. make it possible to dynamically increase the per-user vote limit (not decreasing it, though, for those votes might already be cast)

**Comment by polatengin** [comment]
this feature added by #129 

it'll be included in the next release of the extension (I'm planning to publish a new version on January 28th)
