### ISSUE TITLE
Need the ability to toggle the banners on/off.

### ISSUE THREAD

**Issue by Glenn-Gidlof** [microsoft/vsts-extension-retrospectives#81]
The current iteration has several informational banners at the top of the page.  Yes, we can click the [x] to dismiss them but every time you refresh the page they come back, taking up real-estate on the page.

It would be nice to have an option to toggle these off so they don't keep coming up.  Once the banners have been read it seems a bit unnecessary that they keep coming back.

**Comment by polatengin** [comment]
Thanks for reporting this @Glenn-Gidlof .

It's already captured in #55 , so I'm closing this issue, please feel free to re-open if you think these are not related.

**Comment by Glenn-Gidlof** [comment]
Yes, I believe these two issues are the same.  Thank you for taking a look.

Cheers,

-Glenn
