### ISSUE TITLE
Card backgrounds are now a dark grey which contrasts poorly with black text

### ISSUE THREAD

**Issue by hegold** [microsoft/vsts-extension-retrospectives#82]
![image](https://user-images.githubusercontent.com/13440904/101217681-a2a83a80-3636-11eb-97c3-5a5e9de298c6.png)

This seems to be a recent change. It would be nice to return to the previous colours.

**Comment by hegold** [comment]
An even bigger problem for the vote counts:

![image](https://user-images.githubusercontent.com/13440904/101218144-63c6b480-3637-11eb-8b14-ab972a41318b.png)

**Comment by EmanMos** [comment]
Thanks @polatengin. May I ask why the board's UI was changed at first place? Were there any bugs already in the old UI?
The old UI of the board was resembling the UI of the normal sprint boards, which gave consistency while using Azure devops.
Can you please consider that? At least the inline vertical and horizontal lines to be the same color as the sprint taskboard.

Thank you so much for the effort you are putting here, much appreciated for all the users using this nice tool.

**Comment by polatengin** [comment]
> May I ask why the board's UI was changed at first place? Were there any bugs already in the old UI?

Hi @EmanMos , actually, I wasn't trying to change the UI , I made the extension support your theme selection.

All the colors, sizes, etc. was hard-coded , now they're coming from css variables, so if you change your theme to "Dark" for example, UI will display in dark tones.

All the functionality and layout should be stay as-is, did I made an unintentional change and couldn't notice? 🤦‍♂️

**Comment by EmanMos** [comment]
> > May I ask why the board's UI was changed at first place? Were there any bugs already in the old UI?
> 
> Hi @EmanMos , actually, I wasn't trying to change the UI , I made the extension support your theme selection.
> 
> All the colors, sizes, etc. was hard-coded , now they're coming from css variables, so if you change your theme to "Dark" for example, UI will display in dark tones.
> 
> All the functionality and layout should be stay as-is, did I made an unintentional change and couldn't notice? 🤦‍♂️


Well, actually, the layout is not as-is, it has changed.
The border and inline lines became grey instead of white, and the font text became grey instead of black, so those make the board looks weird now.
![image](https://user-images.githubusercontent.com/67954813/101336855-3f5b1a00-387b-11eb-8905-4b1cd849ca85.png)

**Comment by polatengin** [comment]
by layout, I mean, locations of UI elements. that shouldn't be changed with recent updates.

but colors, you're right. they changed to support Azure DevOps Themes. I'm gonna make some updates to improve color contrast.

Stay tuned 👍

**Comment by EmanMos** [comment]
@polatengin Yeah sorry, I meant UI changes, the layout is as-is.
Thank you so much for taking care of that, yeah my teams would love to see the old UI.

**Comment by hegold** [comment]
@polatengin Thanks for working on this! I too would love to see better contrast, and I'll also mention that on the "Act" tab, part of the border is now missing from the cards (lower left):

![image](https://user-images.githubusercontent.com/13440904/101409894-632a5a00-3893-11eb-9c93-90ab3ef7e407.png)

**Comment by EmanMos** [comment]
Also, when you hover on the tabs of the retro board, the tabs becomes black.

![image](https://user-images.githubusercontent.com/67954813/101457529-f3b97680-3935-11eb-84bc-a0011c1d8185.png)

**Comment by EmanMos** [comment]
@polatengin Sorry, but do we have an expected date to get the UI fixed? The above 2 comments (text is not readable because it changed to grey, and the highlighted text changed to black).
