### ISSUE TITLE
Board Not Found

### ISSUE THREAD

**Issue by lonevvolf** [microsoft/vsts-extension-retrospectives#821]
**Describe the bug**
For some users, they can create a Retrospective, but when sharing the link, other users get the message:
Could not find the board specified in the url.

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[X] No

If Yes, what version of the extension?

**To Reproduce**

1. Create a Retrospective with a non-admin user
2. Copy the link and open as another non-admin user
3. See error

**Expected behavior**
All users with permissions in the Team/Project should see the Retrospective

**Screenshots**
![image](https://github.com/user-attachments/assets/d0f5f515-509a-4e62-9bc8-6b7871163bb6)

**What screen type are you seeing this on ?**
[X] Desktop
[ ] Mobile

**Additional context**

**Comment by maoravec** [comment]
we have same issue - board is missing after upgrade last Friday

**Comment by PratMoha** [comment]
Same issue on my end as well.

**Comment by polatengin** [comment]
I think the PR #829 solves this issue too. please feel free to reopen if you see the problem still exists

**Comment by PratMoha** [comment]
Still facing the issue, the board is not loading...

**Comment by arthis-git** [comment]
The Board is still missing
