### ISSUE TITLE
Retrospective Board becomes inactive when a "Feedback" card is Deleted.

### ISSUE THREAD

**Issue by jasonbash01** [microsoft/vsts-extension-retrospectives#825]
**Describe the bug**
When a "Feedback" card is added to the Retrospective board and then Deleted.   The Retrospective board becomes inactive.  The retro board shows that it exists; but the columns and feedback is lost.  The screen becomes blank, and I am unable to Delete Retrospective board.

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[X] No

If Yes, what version of the extension?

**To Reproduce**
1) Create a new Retrospective Board
2) Enter a Feedback card
3) click on the upper right "3-Dots" ellipsis
4) Delete Feedback (select "Delete Feedback")
5) Refresh Screen
This will delete the feedback and also disable the Retrospective board.  Columns, Feedback, and entire Retro Board is blank.   Unable to "Delete" board by clicking the "Top Ellipsis" and "Delete retrospective"

**Expected behavior**
When the Feedback was deleted, it should have only deleted that single Feedback card.   Instead, the entire retro board becomes blank and inactive.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7addbd5-1773-4c11-b540-5005c44cf71b)
![image](https://github.com/user-attachments/assets/c2a82a59-87f5-48a0-81d1-7811b3944e04)
![image](https://github.com/user-attachments/assets/d14cb01d-4d2c-47dc-ad4e-c29b04e1d7a0)

**What screen type are you seeing this on ?**
[X ] Desktop
[ ] Mobile

**Additional context**

**Comment by jasonbash01** [comment]
It appears that the issue has been resolved with the Retro Boards not disappearing when a Feedback card is "Deleted" from the Retro board.   BUT - The issue still remains that we are unable to "Delete" the old Retro Boards that were cleared out from this issue.   As seen in the last screen-shot - That Delete shows "Active" bug the user is unable to "Click" and "Delete" that board that was impacted by this initial defect. (Delete Button is Inactive - Although it shows active - Can Not Click)

**Comment by polatengin** [comment]
thanks for reporting this issue.

I could be able to repro it on my environment, I'll fix it as soon as possible, and I'll release the fix as a new version
