### ISSUE TITLE
Retrospective Boards are missing and only available in history

### ISSUE THREAD

**Issue by JFriedman09** [microsoft/vsts-extension-retrospectives#826]
**Describe the bug**
"When I view the Retrospectives Home page, all of our boards with feedback are missing. They were available last Friday 8/30. Now, I can only see the history and it will let me create a new one but I can't access the existing ones. The history is a summary with metrics but the actual feedback recorded and summary is no longer available."

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[X ] No

If Yes, what version of the extension?

**To Reproduce**

1. Go to 'Retrospectives'
2. Click on 'Drop-down to select team'
3. Create Board is the only button available

**Expected behavior**
When I view the Retrospectives Home page, I should be able to see all of my boards with feedback. 

**Screenshots**
![image](https://github.com/user-attachments/assets/3760f828-6fa1-463f-bf64-0fe211a0cf6b)
![image](https://github.com/user-attachments/assets/29ef59e9-ec41-48df-aa6a-b7dd33e99f87)

**What screen type are you seeing this on ?**
[X ] Desktop
[ ] Mobile

**Additional context**
User reporting this issue is the project administrator and has "basic" access level.

**Comment by lLunova** [comment]
I am having the exact same issue

**Comment by JFriedman09** [comment]
@polatengin This was marked as closed, but it is still not working as expected. All of our boards are still in history and not viewable. None were marked as archived.
