### ISSUE TITLE
Submit button not working in Team Assessment Retrospective

### ISSUE THREAD

**Issue by Alfadbhq** [microsoft/vsts-extension-retrospectives#885]
**Describe the bug**
Submit button not working in Team Assessment Retrospective

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x ] No

If Yes, what version of the extension?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If you have any developer console information
that feels relevant, that is also helpful!
![Image](https://github.com/user-attachments/assets/63c495ae-1449-4a1f-accc-ea5fa4364f95)

**What screen type are you seeing this on ?**
[ ] Desktop
[ ] Mobile

**Additional context**

**Comment by NativeD3V** [comment]
![Image](https://github.com/user-attachments/assets/70d8b040-aeed-4c86-8482-7978a63792ca)

**Comment by LeonidLevin** [comment]
Same here. Please, fix!

**Comment by jverhuls** [comment]
Same here. Please fix

**Comment by paulschermers** [comment]
Same here, please fix. Thanks in advance

**Comment by Alfadbhq** [comment]
Hi Engin, still having the same issue

**Comment by Alfadbhq** [comment]
Hi @polatengin 

We have a lot of ADO Boards users using the Retrospectives at the end of the Sprint and still not able to Submit Team Assessment. Hoping for the immediate fix of the issue.

**Comment by paulschermers** [comment]
How can we enforce the update of an extension to verify? Our DevOps environment (SaaS) is still running the old version.

**Comment by shawnvdberg** [comment]
We have the same problem for some time. Please fix.

**Comment by lacalladine** [comment]
also having issue against 1.92.24, if there is a way to push fix, please advise.
