### ISSUE TITLE
When multiple access to the retrospective page occurs, the page is not responding & not retrieving 

### ISSUE THREAD

**Issue by renjiniravi** [microsoft/vsts-extension-retrospectives#9]

**Comment by mpth** [comment]
Can you share any more information like errors logged to the console or failing network calls you observed in the dev tools?

**Comment by renjiniravi** [comment]
we are getting a not responding message & page is not loading when other persons of team are asked to load the page . The message states some thing like this " it is taking too long to respond ......" & the retrospective page is not appearing .

**Comment by renjiniravi** [comment]
we are getting a not responding message & page is not loading when other persons of team are asked to load the page . The message states some thing like this " it is taking too long to respond ......" & the retrospective page is not appearing .

**Comment by osmodies** [comment]
Hi me too have bug  similary, and when i inspect  browser  i did see this:
![image](https://user-images.githubusercontent.com/19317872/81455840-04aec900-9156-11ea-8b07-5cbbc119411d.png)

but it was in Azure Devops Server  update 1

**Comment by mindlessroman** [comment]
Hey folks - this issue is a bit stale. I'll close it out for now since a number of "longer than expected to load" bugs have been resolved in the meantime with recent releases. If there is still a problem, we can check into with a new issue.
