### ISSUE TITLE
It doesn't save column title

### ISSUE THREAD

**Issue by rezarms** [microsoft/vsts-extension-retrospectives#90]
The latest version broke our Retro.
When we add new column and change the title it doesn't save the title and just shows New Column.

**Comment by polatengin** [comment]
I received a similar report , as a workaround, please hit `ENTER` when you set the name for a column. it'll be saved.

I'll fix this issue ASAP.

**Comment by oliveratgithub** [comment]
I had the same pitfall (#89) until I figured you now have to confirm with `Return` 🙈

**Comment by roel4ez** [comment]
duplicate of #91 

Indeed, pressing <enter> or <tab> it works.
