### ISSUE TITLE
Cannot submit team assessment after update 1.92.24

### ISSUE THREAD

**Issue by maxcarl** [microsoft/vsts-extension-retrospectives#901]
**Describe the bug**
The feature for team assessments does not work after the extension got the update for 1.92.24.
I can't select or submit an option in the assessment window without receiving an error in the browser console (no error in GUI).

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x] No

**To Reproduce**

1. Open the team assessment
2. Click on any value in any segment
3. Submit the assessment
4. See error in dev-console

**Expected behavior**
I want to be able to submit the team assessment again.

**What screen type are you seeing this on ?**
[x] Desktop
[ ] Mobile

**Additional info**
Error message in browser
```
Uncaught TypeError: e.find(...) is undefined
    onClick https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    _onClick https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Ve https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Ye https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    To https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    To https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Do https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    No https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Ne https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    No https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    No https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    $t https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Xt https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    unstable_runWithPriority https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Kr https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Re https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
    Qt https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.92.24/1728595356142/dist/reflect-bundle.js:2
reflect-bundle.js:2:1866668
```

**Comment by paulschermers** [comment]
Same issue here: 
https://github.com/microsoft/vsts-extension-retrospectives/issues/885

**Comment by shawnvdberg** [comment]
We have the same problem for some time. Please fix.

**Comment by lacalladine** [comment]
this issue affects all our projects in v1.92.24

**Comment by rjhennessey** [comment]
I am experiencing this same issue.

**Comment by RMattC** [comment]
we have the same issue.  Fix needed ASAP, please!

**Comment by polatengin** [comment]
I fixed the issue yesterday with PR #900 , I just published [v1.92.25](https://github.com/microsoft/vsts-extension-retrospectives/releases/tag/v1.92.25)

Closing this issue now, please feel free to re-open it, if the problem persists 👍

**Comment by paulschermers** [comment]
Thanks for the update, @polatengin.

I’m now able to click 'Submit,' but I’m still getting a pop-up that says: `Please answer all questions before saving`. This is odd because I’ve already answered all the questions. Could you help me troubleshoot this?

![Image](https://github.com/user-attachments/assets/2aa8cdd8-b73d-476f-90e9-d970ac6e86e0)

**Comment by RMattC** [comment]
It's not saving.  I just get the "Please answer..." message.  I refreshed the browser but no hange
