### ISSUE TITLE
Can't submit team assesment, receiving notification 'Please answer all questions before saving'

### ISSUE THREAD

**Issue by paulschermers** [microsoft/vsts-extension-retrospectives#905]
**Describe the bug**
I’m now able to click 'Submit,' at version 1.92.25 but I’m now getting a pop-up that says: `Please answer all questions before saving`. This is odd because I’ve already answered all the questions?

It didn't save the results when I look at the 'Show Retrospective summary'

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x] No

If Yes, what version of the extension?

**To Reproduce**

1. Go to 'Retrospectives.'
2. Click on 'Team Assessment'
3. Check the boxes for every entry
4. Click on 'Submit'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If you have any developer console information
that feels relevant, that is also helpful!

![Image](https://github.com/user-attachments/assets/1c7955c0-487a-4110-a0b1-378f2ef61223)

**What screen type are you seeing this on ?**
[X] Desktop
[ ] Mobile

**Additional context**
These issues seems related:
https://github.com/microsoft/vsts-extension-retrospectives/issues/885
https://github.com/microsoft/vsts-extension-retrospectives/issues/901

**Comment by polatengin** [comment]
Hey @paulschermers , can we jump on a call to troubleshoot the issue?

You can send me a meeting request at polatengin [at] outlook [dot] com

**Comment by paulschermers** [comment]
> Hey [@paulschermers](https://github.com/paulschermers) , can we jump on a call to troubleshoot the issue?
> 
> You can send me a meeting request at polatengin [at] outlook [dot] com

Sure, I've just sent an (teams) invite.

**Comment by dwurth** [comment]
We are having the same issue. Please let us know what the solution is. Thank you.

**Comment by polatengin** [comment]
I released a new version a couple of minutes ago, it must solve this issue.

Please check if you still have the issue, or it's resolved on your environment, too.

**Comment by paulschermers** [comment]
Yes, it does work for me. Thanks @polatengin for this fix
