### ISSUE TITLE
Unable to edit column names when creating / editing retrospectives

### ISSUE THREAD

**Issue by dkamalakaran** [microsoft/vsts-extension-retrospectives#91]
Edit / Create retrospective:
![image](https://user-images.githubusercontent.com/40398428/101399587-abe71080-389d-11eb-8879-70a674436500.png)
Change column names... Save...

You get the default names only. Choosing a template seems to work ok.
![image](https://user-images.githubusercontent.com/40398428/101399666-c6b98500-389d-11eb-8249-79866d4aaa1f.png)

Tried this in Chrome & Edge browser. IE does not seem to load the page at all.

**Comment by roel4ez** [comment]
I've also noticed this issue, but found a work around for now:

After filling out the text, press <TAB> to move the focus out of the textbox. Then saving works as expected.

**Comment by 03165298bl** [comment]
Same issue, using Return does work, so thanks for the work around, however, issue still needs to be resolved
