### ISSUE TITLE
Switching template for retrospective deletes all items.

### ISSUE THREAD

**Issue by hgjura** [microsoft/vsts-extension-retrospectives#94]
I did create a new Retrospective and enter a handful feedback items.
I realized that did not have the right template. Clicked in Edit Retrospective.
Without warning or any other indications, a new Retro gets created and all previous items have been wiped out.

I was expecting that items adapt to the new template. At the least I would expect some warning that items will be remove (Yes/No button and a suggestion to export them to csv).

Switching the template back to the original one, does not restore the item. They seem to be gone forever. And that is a problem.

**Comment by veljko** [comment]
Same thing happened to me:
https://pasteboard.co/JEbEpRF.png
https://pasteboard.co/JEbDSSs.png

Is there any way to recover lost retrospective items?
Thanks

**Comment by polatengin** [comment]
I just added a warning text when you edit board metadata. I hope it adds clarification.

**Comment by agile-fan** [comment]
it's fine to get a warning before @polatengin! But as @hgjura mentioned, I'm missing the created feedback items of the team (s. attach) 
![image](https://user-images.githubusercontent.com/76202798/102594825-02aede80-4117-11eb-80a3-41805bfef2f7.png)
and have got the same question: "Is there any way to recover lost retrospective items?"
So a warning in advance would not help me any more, but a capability to get the cards active/visible again!
Thanks

**Comment by agile-fan** [comment]
apart from that, it's nice to have some templates regarding to retro. More important ist to be flexible and be able to rename or reorganize the feedback categories. Beside the 5 configured templates it should definitely be possible to configure your own mindset., as we used to do that in the past.

**Comment by pyce-lb** [comment]
> Is there any way to recover lost retrospective items?

I found one a few days ago by catching outgoing calls in the browser's developer tools and modifying them to move the lost cards to the new columns. Unfortunately you will need to do it for each lost card one-by-one.
I know not everyone is comfortable with such "tinkering" but I'll try my best to describe the process clear as possible.

(I used Firefox, not sure whether other browsers have all the necessary features.)
1. Go to the Retrospective board in question.
2. Open the browsers (Web) developer tools. (Pressing F12 usually does the trick).
3. Switch to the 'Network' tab if it is not the one opened by default.
![image](https://user-images.githubusercontent.com/23698933/105903045-b57c3180-601f-11eb-82fd-98f16052402a.png)
4. Click on the ellipses next to the name of the board and select 'Export CSV content'
![image](https://user-images.githubusercontent.com/23698933/105903506-3e936880-6020-11eb-9f59-594019538cb1.png)
5. A few lines should appear in the 'Network' tab. These are the outgoing calls (requests) from your browser.
6. We need the one with the **GET** method. Select it then click on the 'Response' tab on the right.
![image](https://user-images.githubusercontent.com/23698933/105906372-e494a200-6023-11eb-8dc7-e0f70240ccc0.png)
7. The text in the 'Response' tab contains all the cards of the board (in json), including the lost ones. Copy this into your favourite text editor, we will need this later.
It should look something like this:
```
{
  "count": 2,
  "value": [
    {
      "boardId": "80b87fa2-2aeb-4ea4-a013-5456b0dae189",
      "columnId": "e74380a3-0b46-441a-bae6-2764ff3ae13b",
      "createdBy": {
        ...
      },
      "createdDate": "2021-01-26T19:35:18.601Z",
      "id": "4c5a74ac-04b2-4ae0-a7a6-5ca739d13f61",
      "title": "Test card 2",
      "voteCollection": {},
      "upvotes": 0,
      "userIdRef": "...",
      "__etag": 1
    },
    {
      "boardId": "80b87fa2-2aeb-4ea4-a013-5456b0dae189",
      "columnId": "ca659149-a89b-4474-8184-37eb5ea5b4d1",
      "createdBy": {
        ...
      },
      "createdDate": "2021-01-26T19:35:14.595Z",
      "id": "5621bf85-6c2a-497f-a7ac-6b5e734c628e",
      "title": "Test card 1",
      "voteCollection": {},
      "upvotes": 0,
      "userIdRef": "...",
      "__etag": 1
    }
  ]
}
```
There are two cards on this board. Each card starts with:
```
{
  "boardId": ...
```
and ends with
```
  "__etag": ...
}
```
8. Now we need to create temporary new card and move it from one column to another.
9. Some new lines should appear again in the 'Network' tab. There should be one with **PATCH** method (probably the last one), select it the click on the 'Request' tab. We will need the **'columnId'** from there (bear in mind your 'columnId' value will differ).
![image](https://user-images.githubusercontent.com/23698933/105908860-05aac200-6027-11eb-8606-6d4d18ad3948.png)
10. Now right click on the request with the **PATCH** method and select 'Edit and Resend'.
11. On the right hand side scroll down and copy one of the lost cards from earlier into the 'Request Body' but **change its 'columnId'** to the one from step 9.
![image](https://user-images.githubusercontent.com/23698933/105916546-5f17ee80-6031-11eb-99f7-995f19175b8f.png)
12. Now scroll back up and click 'Send'.
13. If a new line appears in the 'Network' tab with Status: 200 it means **success!** The next time you reload the board you will should see to lost card in the same column where the temporary card was moved.
You will need to repeat 10-12 for every lost card.
14. Delete the temporary card.

I hope this helps and it's not too late to recover those lost cards. :)
