### ISSUE TITLE
1.92.31 (2024-11-19) does not work at all ("We detected an error in the application")

### ISSUE THREAD

**Issue by yirkha** [microsoft/vsts-extension-retrospectives#956]
**Describe the bug**
I am not able to use the Retrospectives tool at all, it just prints "We detected an error in the application".
```
TypeError: o.useSyncExternalStore is not a function
    x https://ms-devlabs.gallery.vsassets.io/_apis/public/gallery/publisher/ms-devlabs/extension/team-retrospectives/1.92.31/assetbyname/dist/reflect-bundle.js:2
    ToastContainer https://ms-devlabs.gallery.vsassets.io/_apis/public/gallery/publisher/ms-devlabs/extension/team-retrospectives/1.92.31/assetbyname/dist/reflect-bundle.js:2
    aa https://ms-devlabs.gallery.vsassets.io/_apis/public/gallery/publisher/ms-devlabs/extension/team-retrospectives/1.92.31/assetbyname/dist/reflect-bundle.js:2
    Ks https://ms-devlabs.gallery.vsassets.io/_apis/public/gallery/publisher/ms-devlabs/extension/team-retrospectives/1.92.31/assetbyname/dist/reflect-bundle.js:2
...
```

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[x] No

**To Reproduce**

1. Just open any Retrospective link, the root one, or a historical link to a retro from the past or whatever.
2. See error

**Expected behavior**
The tool works as usual.

**Screenshots**
![Image](https://github.com/user-attachments/assets/c10eb5fb-fe39-4281-ae99-03c0e5da9487)

**What screen type are you seeing this on ?**
[x] Desktop
[ ] Mobile

**Additional context**
An update of the extension happened today:
![Image](https://github.com/user-attachments/assets/ff76460f-fe41-4ce2-8828-a4359dffbb56)

**Comment by yirkha** [comment]
The call stack ("o.useSyncExternalStore is not a function" in x() in ToastContainer() in ...) points to **react-toastify**.

https://github.com/fkhadra/react-toastify/issues/1072 says _"the v10 only works with react >= 18"_, but per package.json, this extension/repository is still only on react 17.0.2.

I'd say a React upgrade would be a major change and might need even more testing, which might be hard to get given the limited amount of everybody's time.

So I'd suggest revering the react-toastify upgrade (https://github.com/microsoft/vsts-extension-retrospectives/pull/897).
From what I see in the release notes, there have been plenty of improvements, but no security fixes or similar, so it should be fine to downgrade.

**Comment by MyqlGodfrey** [comment]
Same happening here (same version), ctrl + F5 (sometimes SEVERAL times in a row, gets the page up).  Obviously not a solution, but figured someone might get help from this info.

**Comment by G0rdo** [comment]
Same issue here. Sending positive energy to the support team!

**Comment by TrentBie** [comment]
Same issue with server 2022 update 2

**Comment by polatengin** [comment]
I'm sorry to hear `react-toastify` update causes issues.

I just reverted the update back, waiting for tests to finish, I'll update the extension on the public marketplace 👍

**Comment by polatengin** [comment]
Duplicate as #958

**Comment by westwoodad** [comment]
We also have this issue, how do we update the extension to pick up the revert? I'm not sure how these changes are pushed through the marketplace...

**Comment by OranguTech** [comment]
@westwoodad 

IDK if there's a way to force or "encourage" an update, but ours updated/is working again two days later.
