### ISSUE TITLE
It doesn't save de column name

### ISSUE THREAD

**Issue by gromics** [microsoft/vsts-extension-retrospectives#96]
When i create a new board, it doesn't save de column name, and sets only the default name

**Comment by EmanMos** [comment]
@gromics Until this get resolved, a workaround would be, press enter after you write the column name, it will be saved.

**Comment by EmanMos** [comment]
It is the same issue as # 91:
https://github.com/microsoft/vsts-extension-retrospectives/issues/91

**Comment by agile-fan** [comment]
the workaround from #96 does help.
