### ISSUE TITLE
1.92.31 versions giving 'We detected an error in the application'

### ISSUE THREAD

**Issue by bartelia** [microsoft/vsts-extension-retrospectives#960]
**Describe the bug**
Error opening the retrospective link on all projects with new update to 1.92.31

**Are you using the Retrospectives Tool on-prem?**
[ ] Yes
[X] No

If Yes, what version of the extension?

**To Reproduce**
Update to 1.92.31. Open the retrospectives tab in a project

1. Go to 'Retrospectives'
2. See error

**Expected behavior**
Normal applicaiton behavior

**Screenshots**
![Image](https://github.com/user-attachments/assets/119136ed-625f-4484-b8fa-efa0006ac8f0)

**What screen type are you seeing this on ?**
[X] Desktop
[ ] Mobile

**Additional context**

**Comment by agaray-fdot** [comment]
This has recently been resolved with version 1.92.32 (Latest). #958 shows the conversation and closed comments.

**Comment by msherms2** [comment]
Doesn't look like this has been pushed out yet. When can we expect this?

**Comment by polatengin** [comment]
version 1.92.32 (with this PR #956) must solve this issue.

please feel free to re-open this ticket if you see the problem still exists on your environment 👍
